import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { statSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const indexHtml = await readFile(path.join(root, 'poker', 'index.html'), 'utf8');
const tableV2Html = await readFile(path.join(root, 'poker', 'table-v2.html'), 'utf8');
const tableV2Css = await readFile(path.join(root, 'poker', 'poker-v2.css'), 'utf8');
const consentManagerJs = await readFile(path.join(root, 'js', 'consent-manager.js'), 'utf8');
const consentServicesJs = await readFile(path.join(root, 'js', 'consent-services.js'), 'utf8');
const klaroConfigJs = await readFile(path.join(root, 'js', 'klaro-config.js'), 'utf8');
const adsenseInitJs = await readFile(path.join(root, 'js', 'adsense-init.js'), 'utf8');
const landingConsentManagerJs = await readFile(path.join(root, 'landing', 'js', 'consent-manager.js'), 'utf8');
const landingConsentServicesJs = await readFile(path.join(root, 'landing', 'js', 'consent-services.js'), 'utf8');
const landingKlaroConfigJs = await readFile(path.join(root, 'landing', 'js', 'klaro-config.js'), 'utf8');
const landingAdsenseInitJs = await readFile(path.join(root, 'landing', 'js', 'adsense-init.js'), 'utf8');
const landingIndexHtml = await readFile(path.join(root, 'landing', 'index.html'), 'utf8');
const landingAboutHtml = await readFile(path.join(root, 'landing', 'about.html'), 'utf8');
const landingPrivacyEnHtml = await readFile(path.join(root, 'landing', 'legal', 'privacy.en.html'), 'utf8');
const landingPrivacyPlHtml = await readFile(path.join(root, 'landing', 'legal', 'privacy.pl.html'), 'utf8');
const landingGameJs = await readFile(path.join(root, 'landing', 'js', 'landing-game.js'), 'utf8');
const freedoomHtml = await readFile(path.join(root, 'games-open', 'freedoom', 'index.html'), 'utf8');
const freedoomJs = await readFile(path.join(root, 'games-open', 'freedoom', 'script.js'), 'utf8');
const freedoomCss = await readFile(path.join(root, 'games-open', 'freedoom', 'style.css'), 'utf8');
const headersFile = await readFile(path.join(root, '_headers'), 'utf8');
const netlifyToml = await readFile(path.join(root, 'netlify.toml'), 'utf8');
assert.match(indexHtml, /src="\/js\/build-info\.js" defer/, 'poker index should include build-info bootstrap script');
assert.equal(indexHtml.indexOf('/js/build-info.js') < indexHtml.indexOf('/poker/poker-ws-client.js'), true, 'poker index should load build-info before ws client');
assert.doesNotMatch(indexHtml, /pokerClassicEntry/, 'poker lobby should no longer expose the classic table entry');
assert.match(tableV2Html, /id="pokerV2JoinBtn"/, 'poker table v2 should include live join control');
assert.match(tableV2Html, /id="pokerLobbyLink"/, 'poker table v2 should include a back-to-lobby link in the hamburger menu');
assert.doesNotMatch(tableV2Html, /pokerClassicLink/, 'poker table v2 should not expose the classic table link');
assert.doesNotMatch(tableV2Html, /pokerV2Link/, 'poker table v2 should not expose a self-link in the hamburger menu');
assert.doesNotMatch(tableV2Html, /pokerV2DemoPill/, 'poker table v2 should not render the legacy demo pill');
assert.match(tableV2Html, /src="\/poker\/poker-ws-client\.js" defer/, 'poker table v2 should bootstrap WS client for live runtime');
assert.equal(tableV2Html.indexOf('id="pokerSeatLayer"') < tableV2Html.indexOf('id="pokerDealerChip"'), true, 'dealer chip should be positioned in the full scene after the seat layer');
assert.equal(tableV2Html.indexOf('id="pokerDealerChip"') < tableV2Html.indexOf('class="poker-center-layer"'), true, 'dealer chip should not live inside the center layer');
assert.match(tableV2Css, /\.poker-menu-panel\[hidden\]\{display:none;\}/, 'poker table v2 menu should hard-hide when hidden attribute is present');
assert.match(tableV2Css, /\.poker-action-bar\{position:fixed; right:max\(10px, env\(safe-area-inset-right\)\); bottom:max\(10px, env\(safe-area-inset-bottom\)\); width:min\(33vw, 196px\); display:grid; grid-template-columns:40px minmax\(0, 1fr\);/, 'poker table v2 action rail should dock to the bottom-right with a left-side vertical amount slider');
assert.doesNotMatch(tableV2Css, /\.poker-seat--hero \.poker-seat-avatar\{[^}]*border-color:/, 'hero avatar should not keep an always-on active ring');
assert.match(tableV2Css, /\.poker-seat--hero\.poker-seat--active \.poker-seat-avatar\{border-color:rgba\(84,245,152,0\.88\);/, 'hero avatar should turn green only on the active turn');
assert.match(tableV2Html, /id="pokerBootSplash"/, 'poker table v2 should render a boot splash to avoid raw HTML flash');
assert.match(tableV2Html, /id="pokerV2AmountValue"/, 'poker table v2 should render a compact amount value for the action slider');
assert.match(consentManagerJs, /#manageCookies, \.manage-cookies, \[data-manage-cookies\]/, 'consent manager should delegate clicks from all manage cookies links');
assert.match(consentManagerJs, /window\.klaro\.show\(window\.klaroConfig, true\)/, 'manage cookies should open the Klaro preference modal');
assert.match(consentServicesJs, /arcadeConsentChanged/, 'consent services should emit consent updates for AdSense slot initialization');
assert.match(klaroConfigJs, /cookieDomain: sharedDomain/, 'Klaro should share consent across matching kcswh.pl subdomains');
assert.match(indexHtml, /js\/vendor\/klaro\/klaro\.js/, 'portal pages should load Klaro');
assert.doesNotMatch(indexHtml, /Cookiebot|data-cookieconsent/, 'portal index should no longer load Cookiebot-managed scripts');
assert.equal(landingConsentManagerJs, consentManagerJs, 'landing deploy should publish the shared consent manager at /js/consent-manager.js');
assert.equal(landingConsentServicesJs, consentServicesJs, 'landing deploy should publish the shared consent services helper at /js/consent-services.js');
assert.equal(landingKlaroConfigJs, klaroConfigJs, 'landing deploy should publish the shared Klaro config at /js/klaro-config.js');
assert.equal(landingAdsenseInitJs, adsenseInitJs, 'landing deploy should publish the AdSense init helper at /js/adsense-init.js');
assert.match(landingIndexHtml, /data-landing-game/, 'landing page should render the mini game surface');
assert.match(landingIndexHtml, /\.\/js\/landing-game\.js/, 'landing page should load the mini game controller');
assert.match(landingGameJs, /landingPixelBest/, 'landing mini game should persist the best score locally');
assert.equal([landingIndexHtml, landingAboutHtml, landingPrivacyEnHtml, landingPrivacyPlHtml].every((html) => html.includes('href="https://play.kcswh.pl/xp.html"')), true, 'landing XP badges should link to the play subdomain XP panel');
assert.equal([landingIndexHtml, landingAboutHtml, landingPrivacyEnHtml, landingPrivacyPlHtml].some((html) => /href="\.\.?\/.*xp\.html"|xp-badge--loading/.test(html)), false, 'landing XP badges should not point to missing local XP pages or show a permanent loading state');
assert.match(freedoomHtml, /id="doomCanvas"/, 'Freedoom should render the Dwasm canvas target');
assert.match(freedoomHtml, /js\/vendor\/klaro\/klaro\.js/, 'Freedoom should use the shared Klaro consent runtime');
assert.doesNotMatch(freedoomHtml, /Cookiebot|cookiebot-manager|js-dos|v8\.js-dos\.com/, 'Freedoom should not depend on Cookiebot or js-dos assets');
assert.match(freedoomJs, /freedoom2\.bin/, 'Freedoom should download the Freedoom Phase 2 archive');
assert.match(freedoomJs, /assets\/freedoom2\.bin/, 'Freedoom should load the local Freedoom archive');
assert.match(freedoomJs, /freedoom2\.wad/, 'Freedoom should boot the Freedoom WAD');
assert.match(freedoomJs, /'-config',\s*'\/arcade-prboomx\.cfg'/, 'Freedoom should boot with the Arcade Hub PrBoom control config');
assert.match(freedoomJs, /'-warp',\s*'1'/, 'Freedoom should start in a playable map instead of the demo loop');
assert.match(freedoomJs, /vendor\/dwasm\/index\.js/, 'Freedoom should use the vendored Dwasm runtime');
assert.doesNotMatch(freedoomJs, /digger\.jsdos|v8\.js-dos\.com|cdn\.dos\.zone/, 'Freedoom should not boot the old Digger/js-dos placeholder');
assert.match(freedoomJs, /setPointerCapture\(activePointerId\)/, 'Freedoom mobile joysticks should capture independent pointer IDs');
assert.doesNotMatch(freedoomJs, /event\.touches\[0\]/, 'Freedoom mobile controls should not read the first global touch');
assert.match(freedoomJs, /key_up\s+0x77/, 'Freedoom PrBoom config should bind forward to W');
assert.match(freedoomJs, /key_down\s+0x73/, 'Freedoom PrBoom config should bind backward to S');
assert.match(freedoomJs, /key_strafeleft\s+0x61/, 'Freedoom PrBoom config should bind strafe-left to A');
assert.match(freedoomJs, /key_straferight\s+0x64/, 'Freedoom PrBoom config should bind strafe-right to D');
assert.match(freedoomJs, /sendKey\('KeyW',\s*shouldMoveUp\)/, 'Freedoom mobile forward control should send the configured forward key');
assert.match(freedoomJs, /sendKey\('KeyA',\s*shouldMoveLeft\)/, 'Freedoom mobile strafe-left control should send the configured strafe key');
assert.match(freedoomJs, /sendKey\('KeyD',\s*shouldMoveRight\)/, 'Freedoom mobile strafe-right control should send the configured strafe key');
assert.match(freedoomJs, /document\.pointerLockElement === \(state\.renderCanvas \|\| elements\.canvas\)/, 'Freedoom desktop pointer lock should follow the runtime canvas');
assert.match(freedoomJs, /target\.requestPointerLock\(\)/, 'Freedoom desktop controls should request pointer lock on the runtime canvas');
assert.match(freedoomJs, /document\.addEventListener\('mousedown', function\(event\) \{\s*if \(event\.__arcadeSynthetic \|\| event\.button !== 0\) return;[\s\S]*sendMouseButton\(0,\s*true\);/, 'Freedoom desktop firing should press the primary mouse button through the runtime input path');
assert.match(freedoomJs, /document\.addEventListener\('mouseup', function\(event\) \{\s*if \(event\.__arcadeSynthetic \|\| event\.button !== 0 \|\| !fireHeld\) return;[\s\S]*sendMouseButton\(0,\s*false\);/, 'Freedoom desktop firing should release the primary mouse button through the runtime input path');
assert.match(freedoomJs, /event\.__arcadeSynthetic = true;/, 'Freedoom synthetic desktop mouse events should be marked to avoid feedback loops');
assert.match(freedoomJs, /window\.addEventListener\('orientationchange'[\s\S]*startGame\(\);/, 'Freedoom should auto-start on page load instead of waiting for a manual Play click');
assert.match(freedoomJs, /movement_mouselook\s+1/, 'Freedoom PrBoom config should enable mouselook for vertical look controls');
assert.match(freedoomJs, /sendMouseMove\(0,\s*Math\.round\(lookVector\.y \* 18\)\)/, 'Freedoom mobile look joystick should drive vertical mouselook');
assert.match(freedoomJs, /document,\s*window/, 'Freedoom synthetic key events should reach the runtime keyboard listeners');
assert.match(freedoomJs, /canvas:\s*renderCanvas/, 'Freedoom runtime should render to an internal canvas instead of the visible presentation canvas');
assert.match(freedoomJs, /ctx\.drawImage\(source,\s*0,\s*0,\s*sourceWidth,\s*sourceHeight,\s*drawX,\s*drawY,\s*drawWidth,\s*drawHeight\)/, 'Freedoom presentation canvas should scale the full runtime frame');
assert.match(freedoomCss, /\.doom-canvas\s*\{[^}]*width:\s*100% !important;[^}]*height:\s*100% !important;/, 'Freedoom canvas should be forced to fit inside the game frame');
assert.match(freedoomCss, /\.freedoom-frame\s*\{[^}]*aspect-ratio:\s*16 \/ 9;/, 'Freedoom frame should match the Dwasm widescreen render aspect');
assert.ok(statSync(path.join(root, 'games-open', 'freedoom', 'assets', 'freedoom2.bin')).size > 7_000_000, 'Freedoom should publish the local Freedoom archive');
assert.match(headersFile, /\/games-open\/freedoom\/\*/, 'Freedoom should have a scoped CSP in _headers');
assert.doesNotMatch(headersFile, /dwasm\.m-h\.org\.uk/, 'Freedoom CSP should not rely on a remote WAD mirror');
assert.match(netlifyToml, /for = "\/games-open\/freedoom\/\*"/, 'Netlify should emit a scoped Freedoom CSP');
assert.doesNotMatch(netlifyToml, /dwasm\.m-h\.org\.uk/, 'Netlify Freedoom CSP should not rely on a remote WAD mirror');
assert.ok(netlifyToml.includes('Content-Security-Policy = "'), 'Netlify deploys should emit a CSP header');
assert.doesNotMatch(netlifyToml, /cookiebot/i, 'Netlify CSP should not require Cookiebot hosts after the Klaro migration');
assert.match(netlifyToml, /for = "\/css\/\*"[\s\S]*?Cache-Control = "public, max-age=0, must-revalidate"/, 'CSS files use stable names and should revalidate after deploys');
assert.match(netlifyToml, /for = "\/js\/\*"[\s\S]*?Cache-Control = "public, max-age=0, must-revalidate"/, 'JS files use stable names and should revalidate after deploys');
const cssHeaderBlock = netlifyToml.match(/\[\[headers\]\]\s+for = "\/css\/\*"[\s\S]*?(?=\n\[\[headers\]\]|$)/)?.[0] || '';
const jsHeaderBlock = netlifyToml.match(/\[\[headers\]\]\s+for = "\/js\/\*"[\s\S]*?(?=\n\[\[headers\]\]|$)/)?.[0] || '';
assert.doesNotMatch(cssHeaderBlock, /immutable/, 'Stable CSS paths must not be cached as immutable');
assert.doesNotMatch(jsHeaderBlock, /immutable/, 'Stable JS paths must not be cached as immutable');
