name: Feature
description: New capability with explicit scope, invariants, and tests.
title: "[FEAT] "
labels: ["type:feature"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - poker-backend
        - poker-ui
        - chips-ledger
        - xp
        - portal-ui
        - infra
        - security
        - tests
        - docs
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: Goal
    validations:
      required: true
  - type: textarea
    id: non_goals
    attributes:
      label: Non-goals
      placeholder: |
        - ...
  - type: checkboxes
    id: invariants
    attributes:
      label: Invariants touched (check all that apply)
      options:
        - label: idempotency / replay safety
        - label: chips ledger balanced / no negative balances
        - label: auth/RLS/CSP/security
        - label: availability / timeouts / retries
        - label: data migration / schema changes
  - type: textarea
    id: ac
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: tests
    attributes:
      label: Tests to add/update
      placeholder: |
        - Add/Update: tests/...
    validations:
      required: true
  - type: textarea
    id: rollout
    attributes:
      label: Rollout / risk notes
      placeholder: |
        - Any feature flags/env vars?
        - Backward compatibility?
        - Monitoring/klog?
