import assert from "node:assert/strict";
import fs from "node:fs";

const migration = fs.readFileSync("supabase/migrations/20260904100000_chips_ledger_closed_human_table_retention.sql", "utf8");
const canaryMigration = fs.readFileSync("supabase/migrations/20260904180000_chips_ledger_closed_human_canary_execute.sql", "utf8");
const policyRlsMigration = fs.readFileSync("supabase/migrations/20260905100000_chips_ledger_closed_human_policy_rls_select.sql", "utf8");
const lifecycleOwnerMigration = fs.readFileSync("supabase/migrations/20260905110000_chips_ledger_closed_human_lifecycle_completion_owner.sql", "utf8");
const lifecycleMarkerRlsMigration = fs.readFileSync("supabase/migrations/20260905120000_chips_ledger_closed_human_lifecycle_marker_rls.sql", "utf8");
const cleanup = fs.readFileSync("ws-server/poker/persistence/closed-table-cleanup.mjs", "utf8");

assert.match(migration, /human_retention_complete_at timestamptz/);
assert.match(migration, /chips_assert_closed_human_table_lifecycle_gate/);
assert.match(migration, /stage-ledger-auto-retention-30d-v1/);
assert.match(migration, /stage-ledger-closed-human-table-retention-30d-v1/);
assert.doesNotMatch(migration, /replay_transaction/);
assert.doesNotMatch(migration, /chips\.bot_registry_cleanup/);
assert.match(canaryMigration, /chips_authorize_closed_human_table_retention_canary\(\s*p_batch_id bigint,\s*p_confirmation text/);
assert.match(canaryMigration, /p_confirmation is distinct from \('GO ' \|\| p_batch_id::text\)/);
assert.match(canaryMigration, /stage-ledger-closed-human-table-retention-30d-v1/);
assert.match(canaryMigration, /chips\.closed_human_go/);
assert.match(canaryMigration, /destructive_go_at/);
assert.match(canaryMigration, /chips_prune_closed_human_table_archive_batch/);
assert.match(canaryMigration, /chips_assert_closed_human_table_lifecycle_gate\(/);
assert.match(canaryMigration, /policy\.enabled is true[\s\S]*policy\.activated_at is not null/);
assert.match(canaryMigration, /p_approved_batch_id is distinct from batch\.batch_id/);
assert.match(canaryMigration, /p_execute is false or prune_result->>'state' = 'already_pruned'/);
assert.doesNotMatch(canaryMigration, /chips_complete_closed_human_table_retention/);
assert.doesNotMatch(canaryMigration, /7575202818581710058/);
assert.equal((policyRlsMigration.match(/\bcreate policy\b/gi) || []).length, 1);
assert.match(policyRlsMigration, /create policy chips_stage_closed_human_table_retention_policy_pruner_select/);
assert.match(policyRlsMigration, /on public\.chips_stage_closed_human_table_retention_policy/);
assert.match(policyRlsMigration, /for select/);
assert.match(policyRlsMigration, /to chips_ledger_archive_pruner/);
assert.match(policyRlsMigration, /using \(policy_id = 'stage-ledger-closed-human-table-retention-30d-v1'\)/);
assert.doesNotMatch(policyRlsMigration, /for (insert|update|delete)|with check|to (public|anon|authenticated|service_role)/i);
assert.match(lifecycleOwnerMigration, /alter function public\.chips_complete_closed_human_table_retention\(uuid, timestamptz\)\s+owner to chips_ledger_archive_pruner/);
assert.match(lifecycleOwnerMigration, /grant update \(human_retention_complete_at\) on public\.poker_tables to chips_ledger_archive_pruner/);
assert.doesNotMatch(lifecycleOwnerMigration, /create or replace function|create policy|insert into|update public|delete from/i);
assert.equal((lifecycleMarkerRlsMigration.match(/\bcreate policy\b/gi) || []).length, 1);
assert.match(lifecycleMarkerRlsMigration, /create policy chips_archive_pruner_human_retention_marker_update/);
assert.match(lifecycleMarkerRlsMigration, /on public\.poker_tables[\s\S]*for update[\s\S]*to chips_ledger_archive_pruner/);
assert.match(lifecycleMarkerRlsMigration, /using \([\s\S]*has_human_participant is true[\s\S]*human_retention_complete_at is null[\s\S]*chips\.closed_human_lifecycle/);
assert.match(lifecycleMarkerRlsMigration, /with check \([\s\S]*has_human_participant is true[\s\S]*human_retention_complete_at is not null[\s\S]*chips\.closed_human_lifecycle/);
assert.doesNotMatch(lifecycleMarkerRlsMigration, /chips_archive_pruner_tables_marker_update|for (select|insert|delete)|to (public|anon|authenticated|service_role)/i);
assert.match(cleanup, /t\.has_human_participant is true and t\.human_retention_complete_at is not null/);
assert.match(cleanup, /t\.has_human_participant is not true and t\.bot_only_retention_complete_at is not null/);

process.stdout.write("chips-ledger-closed-human-retention contracts passed\n");
