import assert from "node:assert/strict";
import fs from "node:fs";

const diagnostic = fs.readFileSync("scripts/ops/chips-ledger-stage-timeout-diagnostic.mjs", "utf8");
const workflow = fs.readFileSync(".github/workflows/chips-ledger-stage-timeout-diagnostic.yml", "utf8");

assert.match(diagnostic, /set transaction isolation level repeatable read, read only/);
assert.match(diagnostic, /explain \(format json, verbose true, costs true, settings true\)/i);
assert.doesNotMatch(diagnostic, /EXPLAIN\s*\([^)]*ANALYZE/i);
assert.match(diagnostic, /set local statement_timeout = '\$\{REPLAY_STATEMENT_TIMEOUT_MS\}ms'/);
assert.match(diagnostic, /selectorReplay/);
assert.match(diagnostic, /runBotOnlyTableIdentitySummaryDiagnostic/);
assert.match(diagnostic, /runExport/);
assert.match(diagnostic, /verifyLocalArchive/);
assert.match(diagnostic, /diagnoseTableIdentitySummary/);
assert.match(diagnostic, /statement_timeout_ms: REPLAY_STATEMENT_TIMEOUT_MS/);
assert.doesNotMatch(diagnostic, /boundedProbe|DIAGNOSTIC_PROBE_TIMEOUT_MS/);
assert.match(diagnostic, /candidate_result_limit: STAGE_MAX_BATCH_SIZE/);
assert.match(diagnostic, /EXACT_BOT_ONLY_DIAGNOSTIC_BATCH_ID = "481"/);
assert.match(diagnostic, /--batch-id 481/);
assert.match(diagnostic, /BOT_ONLY_PROOF_TARGET_TRANSACTIONS_EXPLAIN_SQL/);
assert.match(diagnostic, /candidate_transaction_ids as \(/);
assert.match(diagnostic, /from candidate_transaction_ids candidates\s+join public\.chips_transactions transactions on transactions\.id = candidates\.id/s);
assert.match(diagnostic, /registry\.table_id = \$2::uuid/);
assert.match(diagnostic, /entries\.transaction_id/);
assert.doesNotMatch(diagnostic, /target_transactions\s+as\s*\([\s\S]*?from public\.chips_transactions transactions[\s\S]*?transactions\.id = any[\s\S]*?\bor[\s\S]*?public\.chips_entries/s);
assert.match(diagnostic, /BOT_ONLY_PROOF_UNKNOWN_REGISTRY_EXPLAIN_SQL/);
assert.match(diagnostic, /BOT_ONLY_PROOF_REGISTRY_KEY_COMPLETENESS_EXPLAIN_SQL/);
assert.match(diagnostic, /assertExactBotOnlyDiagnosticBatch/);
assert.match(diagnostic, /downloadPrivateArchiveObject/);
assert.match(diagnostic, /buildPruneEvidence/);
assert.match(diagnostic, /proof_helper_definition/);
assert.match(diagnostic, /explain_analyze: false/);
assert.match(diagnostic, /plan_sha256: sqlSha256\(JSON\.stringify\(plan\)\)/);
assert.match(diagnostic, /access_path: planAccessSummary\(plan\)/);
assert.match(diagnostic, /startup_cost: root\["Startup Cost"\]/);
assert.match(diagnostic, /total_cost: root\["Total Cost"\]/);
assert.match(diagnostic, /estimated_rows: root\["Plan Rows"\]/);
assert.doesNotMatch(diagnostic, /plan: rows\[0\]/);
assert.match(diagnostic, /output_contains_sql_parameters: false/);
assert.match(diagnostic, /output_contains_rows: false/);
assert.match(diagnostic, /output_contains_transaction_ids: false/);
assert.match(diagnostic, /output_contains_registry_keys: false/);
assert.match(diagnostic, /storage_access: false/);
assert.doesNotMatch(diagnostic, /\b(?:insert|update|delete|truncate|alter|drop)\s+(?:into\s+)?public\./i);

assert.match(workflow, /workflow_dispatch:/);
assert.doesNotMatch(workflow, /schedule:/);
assert.match(workflow, /SUPABASE_STAGE_DB_URL: \$\{\{ secrets\.SUPABASE_STAGE_DB_URL \}\}/);
assert.match(workflow, /SUPABASE_STAGE_URL: \$\{\{ secrets\.SUPABASE_STAGE_URL \}\}/);
assert.match(workflow, /SUPABASE_STAGE_SERVICE_ROLE_KEY: \$\{\{ secrets\.SUPABASE_STAGE_SERVICE_ROLE_KEY \}\}/);
assert.match(workflow, /DEPLOYED_COMMIT_SHA: \$\{\{ steps\.checkout-sha\.outputs\.sha \}\}/);
assert.match(workflow, /node scripts\/ops\/chips-ledger-stage-timeout-diagnostic\.mjs/);
assert.match(workflow, /bot_only_batch_id:/);
assert.match(workflow, /BOT_ONLY_DIAGNOSTIC_BATCH_ID: \$\{\{ inputs\.bot_only_batch_id \}\}/);
assert.match(workflow, /args=\(\)/);
assert.match(workflow, /args\+=\(--batch-id/);
assert.doesNotMatch(workflow, /--execute|CHIPS_LEDGER_BOT_ONLY_EXECUTE|SUPABASE_PROD_/);

process.stdout.write("chips-ledger-stage-timeout-diagnostic guard passed\n");
