import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import postgres from "postgres";
import {
  assertActivePokerTableCapacity,
  assertPendingPokerTableCapacity,
  countActivePokerTables,
  countPendingPokerTables,
  lockUserTableSlots,
  MAX_ACTIVE_POKER_TABLES,
  MAX_PENDING_POKER_TABLES,
} from "../../shared/poker-domain/table-participation.mjs";
import { hasPokerPoolSchema } from "../../shared/poker-domain/bot-access.mjs";
import { refillPool, utcBucketStart } from "../../scripts/ops/poker-bot-pool-refill.mjs";

const dbUrl = process.env.POKER_POLICY_TEST_DB_URL || "";
const allowNonTestDb = process.env.POKER_POLICY_ALLOW_NONTEST_DB === "1";
const sourcePath = path.join(process.cwd(), "shared", "poker-domain", "table-participation.mjs");
const migrationPath = path.join(process.cwd(), "supabase", "migrations", "20260927100000_poker_bot_quarantine_policy.sql");

const BASE_SCHEMA = `
create extension if not exists pgcrypto;
do $$
begin
  create role anon;
exception when duplicate_object then null;
end $$;
do $$
begin
  create role authenticated;
exception when duplicate_object then null;
end $$;
create table if not exists public.chips_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  system_key text,
  account_type text not null,
  status text not null default 'active',
  balance bigint not null default 0,
  next_entry_seq bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists fixture_chips_accounts_system_key_uidx
  on public.chips_accounts (system_key) where system_key is not null;
create table if not exists public.chips_transactions (
  id uuid primary key default gen_random_uuid(),
  tx_type text not null,
  idempotency_key text not null unique,
  payload_hash text not null default 'fixture',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.chips_entries (
  id bigint generated by default as identity primary key,
  transaction_id uuid not null references public.chips_transactions (id) on delete cascade,
  account_id uuid not null references public.chips_accounts (id),
  entry_seq bigint,
  amount bigint not null,
  metadata jsonb not null default '{}'::jsonb
);
create table if not exists public.poker_tables (
  id uuid primary key default gen_random_uuid(),
  stakes jsonb not null default '{}'::jsonb,
  buy_in bigint not null default 100,
  max_players int not null default 6,
  status text not null default 'OPEN',
  created_by uuid,
  has_human_participant boolean not null default false,
  lifecycle_kind text not null default 'STANDARD',
  is_slow_only boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now()
);
create table if not exists public.poker_seats (
  table_id uuid not null references public.poker_tables (id) on delete cascade,
  user_id uuid not null,
  seat_no int not null,
  status text not null default 'ACTIVE',
  stack bigint not null default 0,
  is_bot boolean not null default false,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  primary key (table_id, seat_no),
  unique (table_id, user_id)
);
create table if not exists public.poker_state (
  table_id uuid primary key references public.poker_tables (id) on delete cascade,
  version bigint not null default 0,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create index if not exists fixture_poker_seats_table_id_idx on public.poker_seats (table_id);
`;

let migrationSqlPromise;
async function migrationSql() {
  migrationSqlPromise ||= fs.readFile(migrationPath, "utf8");
  return migrationSqlPromise;
}

function fixtureUuid(value) {
  return `00000000-0000-4000-8000-${Number(value).toString(16).padStart(12, "0")}`;
}

function makeBarrier(size) {
  let arrived = 0;
  let release;
  const released = new Promise((resolve) => { release = resolve; });
  return async () => {
    arrived += 1;
    if (arrived === size) release();
    await released;
  };
}

function planNodes(node, result = []) {
  if (!node || typeof node !== "object") return result;
  if (typeof node["Node Type"] === "string") result.push(node);
  for (const child of Array.isArray(node.Plans) ? node.Plans : []) planNodes(child, result);
  return result;
}

async function ensureFixture(sql) {
  const rows = await sql`select
    to_regclass('public.poker_access_policy') as policy_table,
    to_regclass('public.poker_seats_user_id_active_human_idx') as active_index,
    to_regclass('public.poker_tables_created_by_pending_standard_idx') as pending_index;`;
  if (!rows[0]?.policy_table || !rows[0]?.active_index || !rows[0]?.pending_index) {
    await sql.unsafe(BASE_SCHEMA);
    await sql.unsafe(await migrationSql());
  }
  await sql.unsafe(`
    truncate public.poker_seats, public.poker_state, public.poker_tables,
      public.chips_entries, public.chips_transactions, public.chips_accounts
    restart identity cascade;
  `);
  await sql.unsafe(`
    insert into public.chips_accounts (account_type, system_key, status, balance)
    values
      ('SYSTEM', 'GENESIS', 'active', 1000000000),
      ('SYSTEM', 'POKER_BOT_BANKROLL_100', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_100', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_500', 'active', 0);
  `);
}

async function withFixture(callback, { initialize = true } = {}) {
  const sql = postgres(dbUrl, { max: 24, idle_timeout: 0, connect_timeout: 5 });
  try {
    const databaseRows = await sql`select current_database() as name;`;
    const databaseName = String(databaseRows?.[0]?.name || "");
    if (!allowNonTestDb) assert.match(databaseName, /(?:^|_)test$/i, "refusing transaction fixture outside a test database");
    if (initialize) await ensureFixture(sql);
    return await callback(sql);
  } finally {
    await sql.end({ timeout: 5 });
  }
}

async function countSlots(sql, userId) {
  return sql.begin(async (tx) => ({
    active: await countActivePokerTables(tx, userId),
    pending: await countPendingPokerTables(tx, userId),
  }));
}

async function countArtifacts(sql, tableId) {
  const rows = await sql.unsafe(`
    select
      (select count(*)::int from public.poker_tables where id = $1::uuid) as tables,
      (select count(*)::int from public.poker_state where table_id = $1::uuid) as states,
      (select count(*)::int from public.chips_accounts where system_key = $2) as escrows;
  `, [tableId, `POKER_TABLE:${tableId}`]);
  return {
    tables: Number(rows[0]?.tables || 0),
    states: Number(rows[0]?.states || 0),
    escrows: Number(rows[0]?.escrows || 0),
  };
}

async function createPending(sql, userId, tableId, { barrier = null, failAfterInsert = false } = {}) {
  try {
    return await sql.begin(async (tx) => {
      if (barrier) await barrier();
      await lockUserTableSlots(tx, userId);
      await assertPendingPokerTableCapacity(tx, userId);
      await tx.unsafe(`
        insert into public.poker_tables
          (id, stakes, buy_in, max_players, status, created_by, has_human_participant, lifecycle_kind)
        values ($1::uuid, '{}'::jsonb, 100, 6, 'OPEN', $2::uuid, false, 'STANDARD');
      `, [tableId, userId]);
      await tx.unsafe(`
        insert into public.poker_state (table_id, version, state)
        values ($1::uuid, 0, $2::jsonb);
      `, [tableId, { seats: [], stacks: {} }]);
      await tx.unsafe(`
        insert into public.chips_accounts (account_type, system_key, status, balance)
        values ('ESCROW', $1, 'active', 0);
      `, [`POKER_TABLE:${tableId}`]);
      if (failAfterInsert) throw new Error("fixture_create_rollback");
      return { ok: true, tableId };
    });
  } catch (error) {
    return { ok: false, code: error?.code || error?.message || "transaction_failed", tableId };
  }
}

async function authoritativeJoin(sql, userId, tableId, { barrier = null } = {}) {
  try {
    return await sql.begin(async (tx) => {
      if (barrier) await barrier();
      await lockUserTableSlots(tx, userId);
      const existingRows = await tx.unsafe(`
        select table_id, seat_no, stack
        from public.poker_seats
        where table_id = $1::uuid and user_id = $2::uuid and is_bot = false
        limit 1;
      `, [tableId, userId]);
      if (existingRows[0]) {
        await tx.unsafe("update public.poker_seats set last_seen_at = now() where table_id = $1::uuid and user_id = $2::uuid;", [tableId, userId]);
        return { ok: true, kind: "rejoin", tableId };
      }
      await assertActivePokerTableCapacity(tx, userId);
      const tableRows = await tx.unsafe("select id from public.poker_tables where id = $1::uuid and status = 'OPEN' for update;", [tableId]);
      if (!tableRows[0]) throw new Error("table_not_found");
      const stateRows = await tx.unsafe("select state from public.poker_state where table_id = $1::uuid for update;", [tableId]);
      const state = stateRows[0]?.state && typeof stateRows[0].state === "object" ? stateRows[0].state : { seats: [], stacks: {} };
      const nextState = {
        ...state,
        seats: [...(Array.isArray(state.seats) ? state.seats : []), { userId, seatNo: 1, isBot: false, stack: 100 }],
        stacks: { ...(state.stacks && typeof state.stacks === "object" ? state.stacks : {}), [userId]: 100 },
      };
      await tx.unsafe(`
        insert into public.poker_seats (table_id, user_id, seat_no, status, stack, is_bot)
        values ($1::uuid, $2::uuid, 1, 'ACTIVE', 100, false);
      `, [tableId, userId]);
      await tx.unsafe(`
        update public.poker_tables
        set has_human_participant = true, updated_at = now(), last_activity_at = now()
        where id = $1::uuid;
      `, [tableId]);
      await tx.unsafe("update public.poker_state set state = $2::jsonb, version = version + 1, updated_at = now() where table_id = $1::uuid;", [tableId, nextState]);
      await tx.unsafe(`
        insert into public.chips_transactions (tx_type, idempotency_key, payload_hash, metadata)
        values ('BUY_IN', $1, 'fixture-buy-in', $2::jsonb);
      `, [`fixture-buy-in:${tableId}:${userId}`, { tableId, userId }]);
      return { ok: true, kind: "fresh", tableId };
    });
  } catch (error) {
    return { ok: false, code: error?.code || error?.message || "transaction_failed", tableId };
  }
}

async function insertRefillFixtureTransaction(tx, { idempotencyKey, metadata, entries }) {
  const rows = await tx.unsafe(`
    insert into public.chips_transactions (tx_type, idempotency_key, payload_hash, metadata)
    values ('MINT', $1, 'fixture-refill', $2::jsonb)
    returning id;
  `, [idempotencyKey, metadata]);
  for (const entry of entries) {
    const accountRows = await tx.unsafe("select id from public.chips_accounts where account_type = $1 and system_key = $2 for update;", [entry.accountType, entry.systemKey]);
    assert.equal(accountRows.length, 1, `fixture account ${entry.systemKey} must exist`);
    await tx.unsafe(`
      insert into public.chips_entries (transaction_id, account_id, amount, metadata)
      values ($1::uuid, $2::uuid, $3, '{}'::jsonb);
    `, [rows[0].id, accountRows[0].id, entry.amount]);
    await tx.unsafe("update public.chips_accounts set balance = balance + $2 where id = $1::uuid;", [accountRows[0].id, entry.amount]);
  }
  return { transaction: { id: rows[0].id } };
}

test("poker table slot queries keep bounded user-leading and creator-leading contracts", async () => {
  const source = await fs.readFile(sourcePath, "utf8");
  assert.match(source, /from public\.poker_seats s[\s\S]*where s\.user_id = \$1[\s\S]*limit \$\{boundedLimit\}/);
  assert.match(source, /from public\.poker_tables t[\s\S]*where t\.created_by = \$1[\s\S]*limit \$\{boundedLimit\}/);
  assert.match(source, /select distinct s\.table_id/);
  assert.match(source, /public\.poker_state ps[\s\S]*state -> 'seats'[\s\S]*state -> 'stacks'/);
  assert.match(source, /not exists \([\s\S]*public\.poker_seats/);
  assert.match(source, /not exists \([\s\S]*public\.chips_transactions/);
  assert.equal((source.match(/MAX_ACTIVE_POKER_TABLES = 4/g) || []).length, 1);
  assert.equal((source.match(/MAX_PENDING_POKER_TABLES = 4/g) || []).length, 1);
});

test("disposable PostgreSQL capability detects legacy schema then the committed migration on the next transaction", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    await sql.unsafe(BASE_SCHEMA);
    // Permit rerunning this destructive fixture in the same disposable test DB.
    await sql.unsafe("drop table if exists public.poker_access_policy;");
    await sql.begin(async (tx) => {
      assert.equal(await hasPokerPoolSchema(tx), false);
      assert.equal(await hasPokerPoolSchema(tx), false);
      assert.equal(Number((await tx`select 1 as usable;`)[0].usable), 1,
        "capability detection must not leave the legacy transaction aborted");
    });
    await sql.begin(async (tx) => tx.unsafe(await migrationSql()));
    await sql.begin(async (tx) => {
      assert.equal(await hasPokerPoolSchema(tx), true,
        "an earlier negative result must not be cached across transactions");
      const rows = await tx`select slow_threshold_ch from public.poker_access_policy where id = 1;`;
      assert.equal(Number(rows[0].slow_threshold_ch), 1_000_000_000);
    });
  }, { initialize: false });
});

test("disposable PostgreSQL proves concurrent Create/JOIN 4+4 limits, rejection and funded rejoin", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    const userId = fixtureUuid(1);
    const pendingBarrier = makeBarrier(8);
    const pendingResults = await Promise.all(
      Array.from({ length: 8 }, (_, index) => createPending(sql, userId, fixtureUuid(100 + index), { barrier: pendingBarrier })),
    );
    assert.equal(pendingResults.filter((result) => result.ok).length, MAX_PENDING_POKER_TABLES);
    assert.equal(pendingResults.filter((result) => !result.ok && result.code === "pending_table_limit").length, 4);
    assert.deepEqual(await countSlots(sql, userId), { active: 0, pending: 4 });

    const fifthPending = await createPending(sql, userId, fixtureUuid(200));
    assert.equal(fifthPending.ok, false);
    assert.equal(fifthPending.code, "pending_table_limit");
    assert.deepEqual(await countArtifacts(sql, fixtureUuid(200)), { tables: 0, states: 0, escrows: 0 });

    const acceptedPending = pendingResults.filter((result) => result.ok).map((result) => result.tableId);
    const firstJoins = await Promise.all(acceptedPending.slice(0, 2).map((tableId) => authoritativeJoin(sql, userId, tableId)));
    assert.equal(firstJoins.filter((result) => result.ok && result.kind === "fresh").length, 2);
    assert.deepEqual(await countSlots(sql, userId), { active: 2, pending: 2 });

    const additionalPending = await Promise.all([
      createPending(sql, userId, fixtureUuid(300)),
      createPending(sql, userId, fixtureUuid(301)),
    ]);
    assert.equal(additionalPending.filter((result) => result.ok).length, 2);
    assert.deepEqual(await countSlots(sql, userId), { active: 2, pending: 4 });

    const joinCandidates = acceptedPending.slice(2).concat(additionalPending.filter((result) => result.ok).map((result) => result.tableId));
    const boundedJoinBarrier = makeBarrier(joinCandidates.length);
    const boundedJoins = await Promise.all(joinCandidates.map((tableId) => authoritativeJoin(sql, userId, tableId, { barrier: boundedJoinBarrier })));
    assert.equal(boundedJoins.filter((result) => result.ok && result.kind === "fresh").length, 2);
    assert.equal(boundedJoins.filter((result) => !result.ok && result.code === "active_table_limit").length, 2);
    assert.deepEqual(await countSlots(sql, userId), { active: 4, pending: 2 });

    const fifthJoinTable = fixtureUuid(400);
    assert.equal((await createPending(sql, userId, fifthJoinTable)).ok, true);
    const beforeRejectedJoin = await sql`select count(*)::int as count from public.chips_transactions;`;
    const fifthJoin = await authoritativeJoin(sql, userId, fifthJoinTable);
    assert.equal(fifthJoin.ok, false);
    assert.equal(fifthJoin.code, "active_table_limit");
    const afterRejectedJoin = await sql`select count(*)::int as count from public.chips_transactions;`;
    assert.equal(Number(afterRejectedJoin[0].count), Number(beforeRejectedJoin[0].count));
    assert.equal(Number((await sql`select count(*)::int as count from public.poker_seats where user_id = ${userId} and is_bot = false;`)[0].count), 4);

    const activeTableId = acceptedPending[0];
    const beforeRejoin = await sql`select count(*)::int as seats from public.poker_seats where user_id = ${userId};`;
    const fundedRejoin = await authoritativeJoin(sql, userId, activeTableId);
    assert.deepEqual(fundedRejoin, { ok: true, kind: "rejoin", tableId: activeTableId });
    const afterRejoin = await sql`select count(*)::int as seats from public.poker_seats where user_id = ${userId};`;
    assert.equal(Number(afterRejoin[0].seats), Number(beforeRejoin[0].seats));

    const rollbackTable = fixtureUuid(500);
    const rollback = await createPending(sql, userId, rollbackTable, { failAfterInsert: true });
    assert.equal(rollback.ok, false);
    assert.deepEqual(await countArtifacts(sql, rollbackTable), { tables: 0, states: 0, escrows: 0 });
    const markerRows = await sql`select count(*)::int as count from public.poker_tables where id = ${activeTableId} and has_human_participant is true;`;
    assert.equal(Number(markerRows[0].count), 1, "accepted first JOIN must transfer pending to active and set the marker");
  });
});

test("disposable PostgreSQL proves settled automatic SLOW races safely with Admin override", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    const userId = fixtureUuid(2);
    await sql.unsafe(`
      insert into public.chips_accounts (account_type, user_id, status, balance, poker_auto_class, poker_access_override, poker_access_revision)
      values ('USER', $1::uuid, 'active', 1000000000, 'NORMAL', 'AUTO', 1);
    `, [userId]);
    const settledStack = 1000000000;
    await Promise.all([
      sql.begin(async (tx) => {
        await tx.unsafe(`
          update public.chips_accounts account
          set poker_auto_class = case
                when $2::bigint >= policy.slow_threshold_ch then 'SLOW'
                else account.poker_auto_class
              end,
              poker_auto_slow_at = case
                when $2::bigint >= policy.slow_threshold_ch then coalesce(account.poker_auto_slow_at, now())
                else account.poker_auto_slow_at
              end,
              poker_access_revision = account.poker_access_revision + 1
          from public.poker_access_policy policy
          where account.user_id = $1::uuid and account.account_type = 'USER';
        `, [userId, settledStack]);
      }),
      sql.begin(async (tx) => {
        await tx.unsafe(`
          update public.chips_accounts
          set poker_access_override = 'FORCE_NORMAL', poker_access_revision = poker_access_revision + 1
          where user_id = $1::uuid and account_type = 'USER';
        `, [userId]);
      }),
    ]);
    const rows = await sql.unsafe(`
      select poker_auto_class, poker_access_override, poker_access_revision, poker_auto_slow_at
      from public.chips_accounts where user_id = $1::uuid;
    `, [userId]);
    assert.equal(rows[0].poker_auto_class, "SLOW");
    assert.equal(rows[0].poker_access_override, "FORCE_NORMAL");
    assert.equal(Number(rows[0].poker_access_revision), 3);
    assert.ok(rows[0].poker_auto_slow_at, "settled threshold transition must retain durable audit time");
  });
});

test("disposable PostgreSQL proves refill rollback, unknown-commit replay and cross-revision bucket idempotency", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    const now = new Date((await sql`select clock_timestamp() as now;`)[0].now);
    const bucket = utcBucketStart(now);
    const policy = (revision) => ({
      buy_in: 100,
      enabled: true,
      normal_refill_threshold_ch: 1000,
      normal_refill_amount_ch: 300,
      slow_refill_threshold_ch: 1000,
      slow_refill_amount_ch: 300,
      revision,
    });
    const metadataFor = (poolClass, revision) => ({
      purpose: "poker_pool_refill",
      bankrollSystemKey: "POKER_BOT_SLOW_BANKROLL_100",
      buyIn: 100,
      poolClass,
      policyRevision: revision,
      bucket,
    });
    const entries = [
      { accountType: "SYSTEM", systemKey: "GENESIS", amount: -300 },
      { accountType: "SYSTEM", systemKey: "POKER_BOT_SLOW_BANKROLL_100", amount: 300 },
    ];

    await assert.rejects(
      sql.begin((tx) => refillPool({
        tx,
        policy: policy(1),
        poolClass: "SLOW",
        bucket,
        dryRun: false,
        postTransactionFn: async (payload) => {
          await insertRefillFixtureTransaction(payload.tx, {
            idempotencyKey: payload.idempotencyKey,
            metadata: payload.metadata,
            entries: payload.entries,
          });
          throw new Error("fixture_unknown_commit_rolled_back");
        },
      })),
      /fixture_unknown_commit_rolled_back/,
    );
    const afterRollback = await sql`select balance from public.chips_accounts where system_key = 'POKER_BOT_SLOW_BANKROLL_100';`;
    assert.equal(Number(afterRollback[0].balance), 0, "failed transaction must roll back the pool balance");
    assert.equal(Number((await sql`select count(*)::int as count from public.chips_transactions where metadata ->> 'purpose' = 'poker_pool_refill';`)[0].count), 0);

    const concurrentResults = await Promise.all([
      sql.begin((tx) => refillPool({
        tx,
        policy: policy(2),
        poolClass: "SLOW",
        bucket,
        dryRun: false,
        postTransactionFn: (payload) => insertRefillFixtureTransaction(payload.tx, { idempotencyKey: payload.idempotencyKey, metadata: payload.metadata, entries: payload.entries }),
      })),
      sql.begin((tx) => refillPool({
        tx,
        policy: policy(3),
        poolClass: "SLOW",
        bucket,
        dryRun: false,
        postTransactionFn: (payload) => insertRefillFixtureTransaction(payload.tx, { idempotencyKey: payload.idempotencyKey, metadata: payload.metadata, entries: payload.entries }),
      })),
    ]);
    assert.deepEqual(concurrentResults.map((result) => result.status).sort(), ["refilled", "replay"]);
    const refillRows = await sql`select count(*)::int as count from public.chips_transactions where metadata ->> 'purpose' = 'poker_pool_refill' and metadata ->> 'bankrollSystemKey' = 'POKER_BOT_SLOW_BANKROLL_100' and metadata ->> 'bucket' = ${bucket};`;
    assert.equal(Number(refillRows[0].count), 1, "one exact pool/bucket must win across policy revisions");
    const slowBalance = await sql`select balance from public.chips_accounts where system_key = 'POKER_BOT_SLOW_BANKROLL_100';`;
    assert.equal(Number(slowBalance[0].balance), 300);

    const normalPool = "POKER_BOT_BANKROLL_100";
    const normalMetadata = { ...metadataFor("NORMAL", 4), bankrollSystemKey: normalPool, poolClass: "NORMAL" };
    const normalEntries = [
      { accountType: "SYSTEM", systemKey: "GENESIS", amount: -300 },
      { accountType: "SYSTEM", systemKey: normalPool, amount: 300 },
    ];
    await assert.rejects(
      sql.begin((tx) => refillPool({
        tx,
        policy: policy(4),
        poolClass: "NORMAL",
        bucket,
        dryRun: false,
        postTransactionFn: async (payload) => {
          await sql.unsafe(`
            insert into public.chips_transactions (tx_type, idempotency_key, payload_hash, metadata)
            values ('MINT', $1, 'fixture-unknown-commit', $2::jsonb);
          `, [payload.idempotencyKey, { ...normalMetadata, policyRevision: 4 }]);
          throw new Error("fixture_unknown_commit_after_external_commit");
        },
      })),
      /fixture_unknown_commit_after_external_commit/,
    );
    const replay = await sql.begin((tx) => refillPool({
      tx,
      policy: policy(5),
      poolClass: "NORMAL",
      bucket,
      dryRun: false,
      postTransactionFn: (payload) => insertRefillFixtureTransaction(payload.tx, { idempotencyKey: payload.idempotencyKey, metadata: { ...normalMetadata, policyRevision: 5 }, entries: normalEntries }),
    }));
    assert.equal(replay.status, "replay", "retry after an externally committed unknown result must not duplicate MINT");
    const normalRows = await sql`select count(*)::int as count from public.chips_transactions where metadata ->> 'bankrollSystemKey' = ${normalPool} and metadata ->> 'bucket' = ${bucket};`;
    assert.equal(Number(normalRows[0].count), 1);
  });
});

test("local PostgreSQL EXPLAIN confirms bounded indexed active and pending access paths", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    const targetUser = fixtureUuid(9000);
    const unrelatedUser = fixtureUuid(9001);
    for (let index = 0; index < 12; index += 1) {
      await sql.unsafe(`
        insert into public.poker_tables (id, created_by, status, lifecycle_kind, has_human_participant)
        values ($1::uuid, $2::uuid, 'OPEN', 'STANDARD', $3);
      `, [fixtureUuid(10000 + index), targetUser, index < 6]);
      await sql.unsafe(
        "insert into public.poker_state (table_id, state) values ($1::uuid, $2::jsonb);",
        [fixtureUuid(10000 + index), index < 6 ? { seats: [{ userId: targetUser, seatNo: 1 }], stacks: { [targetUser]: 100 } } : { seats: [], stacks: {} }],
      );
      if (index < 6) {
        await sql.unsafe("insert into public.poker_seats (table_id, user_id, seat_no, status, stack, is_bot) values ($1::uuid, $2::uuid, 1, 'ACTIVE', 100, false);", [fixtureUuid(10000 + index), targetUser]);
      }
    }
    await sql.unsafe(`
      insert into public.poker_tables (created_by, status, lifecycle_kind, has_human_participant)
      select $1::uuid, 'OPEN', 'STANDARD', false from generate_series(1, 5000);
    `, [unrelatedUser]);
    await sql.unsafe(`
      insert into public.poker_tables (created_by, status, lifecycle_kind, has_human_participant)
      select $1::uuid, 'OPEN', 'STANDARD', false from generate_series(1, 5000);
    `, [fixtureUuid(9002)]);
    await sql.unsafe(`
      insert into public.poker_seats (table_id, user_id, seat_no, status, stack, is_bot)
      select id, $1::uuid, 1, 'ACTIVE', 100, false
      from public.poker_tables where created_by = $1::uuid limit 5000;
    `, [unrelatedUser]);
    await sql.unsafe(`
      insert into public.poker_state (table_id, state)
      select id, '{"seats": [], "stacks": {}}'::jsonb
      from public.poker_tables where created_by = $1::uuid;
    `, [fixtureUuid(9002)]);
    await sql.unsafe("analyze public.poker_tables; analyze public.poker_seats; analyze public.poker_state; analyze public.chips_transactions;");

    const counts = await countSlots(sql, targetUser);
    assert.deepEqual(counts, { active: 5, pending: 5 }, "counts must stop at the five-row bound");

    const activeExplain = await sql.unsafe(`
      explain (analyze, buffers, format json)
      select count(*)::int as count
      from (
        select distinct s.table_id
        from public.poker_seats s
        join public.poker_tables t on t.id = s.table_id
        where s.user_id = $1::uuid
          and s.status = 'ACTIVE'
          and coalesce(s.is_bot, false) = false
          and coalesce(s.stack, 0) > 0
          and upper(coalesce(t.status, 'OPEN')) not in ('CLOSED', 'TERMINAL')
        limit 5
      ) active_tables;
    `, [targetUser]);
    const pendingExplain = await sql.unsafe(`
      explain (analyze, buffers, format json)
      select count(*)::int as count
      from (
        select t.id
        from public.poker_tables t
        where t.created_by = $1::uuid
          and t.status = 'OPEN'
          and t.lifecycle_kind = 'STANDARD'
          and t.has_human_participant = false
          and exists (select 1 from public.poker_state ps where ps.table_id = t.id and ps.state -> 'seats' = '[]'::jsonb and ps.state -> 'stacks' = '{}'::jsonb)
          and not exists (select 1 from public.poker_seats s where s.table_id = t.id)
          and not exists (select 1 from public.chips_transactions ct where ct.metadata ->> 'tableId' = t.id::text)
        limit 5
      ) pending_tables;
    `, [targetUser]);
    const activePlan = activeExplain[0]["QUERY PLAN"][0];
    const pendingPlan = pendingExplain[0]["QUERY PLAN"][0];
    const activeNodes = planNodes(activePlan.Plan);
    const pendingNodes = planNodes(pendingPlan.Plan);
    assert.ok(activeNodes.some((node) => node["Index Name"] === "poker_seats_user_id_active_human_idx"), "active plan must use user-leading index");
    assert.ok(pendingNodes.some((node) => node["Index Name"] === "poker_tables_created_by_pending_standard_idx"), "pending plan must use creator-leading index");
    for (const nodes of [activeNodes, pendingNodes]) {
      assert.equal(nodes.some((node) => node["Node Type"] === "Seq Scan" && /poker_(seats|tables)/i.test(String(node["Relation Name"] || ""))), false, "fresh count must not scan global seats/tables");
      assert.equal(nodes.some((node) => node["Node Type"] === "Limit" && Number(node["Actual Rows"]) > 5), false, "bounded count must stop at five qualifying rows");
    }
  });
});
