import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import postgres from "postgres";
import {
  assertActivePokerTableCapacity,
  assertPendingPokerTableCapacity,
  countActivePokerTables,
  countPendingPokerTables,
  lockUserTableSlots,
  MAX_ACTIVE_POKER_TABLES,
  MAX_PENDING_POKER_TABLES,
} from "../../shared/poker-domain/table-participation.mjs";
import { hasPokerPoolSchema } from "../../shared/poker-domain/bot-access.mjs";

const dbUrl = process.env.POKER_POLICY_TEST_DB_URL || "";
const allowNonTestDb = process.env.POKER_POLICY_ALLOW_NONTEST_DB === "1";
const sourcePath = path.join(process.cwd(), "shared", "poker-domain", "table-participation.mjs");
const migrationPath = path.join(process.cwd(), "supabase", "migrations", "20260927100000_poker_bot_quarantine_policy.sql");
const tierCatalogMigrationPath = path.join(process.cwd(), "supabase", "migrations", "20260930075513_poker_bot_tier_catalog_expansion.sql");
const hourlyRefillMigrationPath = path.join(process.cwd(), "supabase", "migrations", "20260930211623_poker_bot_pool_refill_hourly.sql");
const refillLockTimeoutMigrationPath = path.join(process.cwd(), "supabase", "migrations", "20260930223409_poker_bot_pool_refill_lock_timeout.sql");
const ledgerFixtureMigrations = [
  "20251218213520_chips_ledger.sql",
  "20251218230000_chips_ledger_fixups.sql",
  "20260116000000_poker_chips_tx_types.sql",
  "20251219002000_chips_accounts_block_negative_balance.sql",
  "20251220000000_chips_allow_genesis_overdraft.sql",
  "20251221000000_chips_seed_treasury_genesis.sql",
  "20251223000000_chips_entry_trigger_fix.sql",
  "20251224000000_chips_transactions_user_id.sql",
  "20260811170000_chips_transaction_idempotency_registry.sql",
];

const BASE_SCHEMA = `
create extension if not exists pgcrypto;
do $$
begin
  create role anon;
exception when duplicate_object then null;
end $$;
do $$
begin
  create role authenticated;
exception when duplicate_object then null;
end $$;
create table if not exists public.chips_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  system_key text,
  account_type text not null,
  status text not null default 'active',
  balance bigint not null default 0,
  next_entry_seq bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists fixture_chips_accounts_system_key_uidx
  on public.chips_accounts (system_key) where system_key is not null;
create table if not exists public.chips_transactions (
  id uuid primary key default gen_random_uuid(),
  tx_type text not null,
  idempotency_key text not null unique,
  payload_hash text not null default 'fixture',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.chips_entries (
  id bigint generated by default as identity primary key,
  transaction_id uuid not null references public.chips_transactions (id) on delete cascade,
  account_id uuid not null references public.chips_accounts (id),
  entry_seq bigint,
  amount bigint not null,
  metadata jsonb not null default '{}'::jsonb
);
create table if not exists public.poker_tables (
  id uuid primary key default gen_random_uuid(),
  stakes jsonb not null default '{}'::jsonb,
  buy_in bigint not null default 100,
  max_players int not null default 6,
  status text not null default 'OPEN',
  created_by uuid,
  has_human_participant boolean not null default false,
  lifecycle_kind text not null default 'STANDARD',
  is_slow_only boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now()
);
create table if not exists public.poker_seats (
  table_id uuid not null references public.poker_tables (id) on delete cascade,
  user_id uuid not null,
  seat_no int not null,
  status text not null default 'ACTIVE',
  stack bigint not null default 0,
  is_bot boolean not null default false,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  primary key (table_id, seat_no),
  unique (table_id, user_id)
);
create table if not exists public.poker_state (
  table_id uuid primary key references public.poker_tables (id) on delete cascade,
  version bigint not null default 0,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create index if not exists fixture_poker_seats_table_id_idx on public.poker_seats (table_id);
`;

let migrationSqlPromise;
async function migrationSql() {
  migrationSqlPromise ||= fs.readFile(migrationPath, "utf8");
  return migrationSqlPromise;
}

async function ensurePoolMigrationFixture(sql) {
  const schemaRows = await sql`select
    to_regclass('public.chips_accounts') as accounts,
    to_regclass('public.chips_transaction_idempotency') as registry,
    to_regprocedure('public.poker_bot_pool_refill_hourly()') as refill_function;`;
  if (schemaRows[0]?.refill_function && schemaRows[0]?.registry) {
    await sql.unsafe(await fs.readFile(refillLockTimeoutMigrationPath, "utf8"));
    return;
  }
  if (schemaRows[0]?.accounts) {
    throw new Error("pool tests require the current full chips schema; run chips migration contracts first");
  }
  await sql.unsafe(`
    do $$ begin
      if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon noinherit; end if;
      if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated noinherit; end if;
      if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role noinherit; end if;
    end $$;
    create schema if not exists auth;
    create table if not exists auth.users (id uuid primary key);
    create or replace function auth.uid() returns uuid language sql stable as $$ select null::uuid $$;
    create schema if not exists extensions;
    create extension if not exists pgcrypto with schema extensions;
  `);
  for (const file of ledgerFixtureMigrations) {
    await sql.unsafe(await fs.readFile(path.join(process.cwd(), "supabase", "migrations", file), "utf8"));
  }
  await sql.unsafe(BASE_SCHEMA);
  await sql.unsafe(await migrationSql());
  await sql.unsafe(await fs.readFile(tierCatalogMigrationPath, "utf8"));
  await sql.unsafe(await fs.readFile(hourlyRefillMigrationPath, "utf8"));
  await sql.unsafe(await fs.readFile(refillLockTimeoutMigrationPath, "utf8"));
}

function fixtureUuid(value) {
  return `00000000-0000-4000-8000-${Number(value).toString(16).padStart(12, "0")}`;
}

function makeBarrier(size) {
  let arrived = 0;
  let release;
  const released = new Promise((resolve) => { release = resolve; });
  return async () => {
    arrived += 1;
    if (arrived === size) release();
    await released;
  };
}

function planNodes(node, result = []) {
  if (!node || typeof node !== "object") return result;
  if (typeof node["Node Type"] === "string") result.push(node);
  for (const child of Array.isArray(node.Plans) ? node.Plans : []) planNodes(child, result);
  return result;
}

async function ensureFixture(sql) {
  await ensurePoolMigrationFixture(sql);
  const rows = await sql`select
    to_regclass('public.poker_access_policy') as policy_table,
    to_regclass('public.poker_seats_user_id_active_human_idx') as active_index,
    to_regclass('public.poker_tables_created_by_pending_standard_idx') as pending_index,
    to_regclass('public.chips_transaction_idempotency') as idempotency_table,
    to_regprocedure('public.poker_bot_pool_refill_hourly()') as refill_function;`;
  if (!rows[0]?.policy_table || !rows[0]?.active_index || !rows[0]?.pending_index) {
    await sql.unsafe(BASE_SCHEMA);
    await sql.unsafe(await migrationSql());
  }
  assert.ok(rows[0]?.idempotency_table, "run the disposable chips migration contract before pool refill tests");
  assert.ok(rows[0]?.refill_function, "the hourly refill migration must be applied before pool refill tests");
  await sql.unsafe("drop trigger if exists fixture_fail_specific_poker_refill_entry_trg on public.chips_entries;");
  await sql.unsafe("drop function if exists public.fixture_fail_specific_poker_refill_entry();");
  await sql.unsafe(`
    truncate public.poker_seats, public.poker_state, public.poker_tables,
      public.chips_entries, public.chips_transaction_idempotency,
      public.chips_transactions, public.chips_accounts
    restart identity cascade;
  `);
  await sql.unsafe(`
    insert into public.chips_accounts (account_type, system_key, status, balance)
    values
      ('SYSTEM', 'GENESIS', 'active', 1000000000),
      ('SYSTEM', 'HOUSE', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_100', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_500', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_100', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_1000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_1000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_5000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_5000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_10000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_10000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_50000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_50000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_100000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_100000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_500000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_500000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_1000000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_1000000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_5000000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_5000000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_BANKROLL_10000000', 'active', 0),
      ('SYSTEM', 'POKER_BOT_SLOW_BANKROLL_10000000', 'active', 0);
  `);
  await sql.unsafe("insert into auth.users (id) values ($1::uuid) on conflict (id) do nothing;", [fixtureUuid(2)]);
  const identityRows = await sql.unsafe("select system_identifier::text as value from pg_catalog.pg_control_system();");
  await sql.unsafe("update public.poker_bot_refill_control set enabled = false, expected_system_identifier = $1 where id = 1;", [identityRows[0].value]);
  await sql.unsafe("update public.poker_bot_tier_policy set enabled = false;");
}

async function withFixture(callback, { initialize = true } = {}) {
  const sql = postgres(dbUrl, { max: 24, idle_timeout: 0, connect_timeout: 5 });
  try {
    const databaseRows = await sql`select current_database() as name;`;
    const databaseName = String(databaseRows?.[0]?.name || "");
    if (!allowNonTestDb) assert.match(databaseName, /(?:^|_)test$/i, "refusing transaction fixture outside a test database");
    if (initialize) await ensureFixture(sql);
    return await callback(sql);
  } finally {
    await sql.end({ timeout: 5 });
  }
}

async function countSlots(sql, userId) {
  return sql.begin(async (tx) => ({
    active: await countActivePokerTables(tx, userId),
    pending: await countPendingPokerTables(tx, userId),
  }));
}

async function countArtifacts(sql, tableId) {
  const rows = await sql.unsafe(`
    select
      (select count(*)::int from public.poker_tables where id = $1::uuid) as tables,
      (select count(*)::int from public.poker_state where table_id = $1::uuid) as states,
      (select count(*)::int from public.chips_accounts where system_key = $2) as escrows;
  `, [tableId, `POKER_TABLE:${tableId}`]);
  return {
    tables: Number(rows[0]?.tables || 0),
    states: Number(rows[0]?.states || 0),
    escrows: Number(rows[0]?.escrows || 0),
  };
}

async function createPending(sql, userId, tableId, { barrier = null, failAfterInsert = false } = {}) {
  try {
    return await sql.begin(async (tx) => {
      if (barrier) await barrier();
      await lockUserTableSlots(tx, userId);
      await assertPendingPokerTableCapacity(tx, userId);
      await tx.unsafe(`
        insert into public.poker_tables
          (id, stakes, buy_in, max_players, status, created_by, has_human_participant, lifecycle_kind)
        values ($1::uuid, '{}'::jsonb, 100, 6, 'OPEN', $2::uuid, false, 'STANDARD');
      `, [tableId, userId]);
      await tx.unsafe(`
        insert into public.poker_state (table_id, version, state)
        values ($1::uuid, 0, $2::jsonb);
      `, [tableId, { seats: [], stacks: {} }]);
      await tx.unsafe(`
        insert into public.chips_accounts (account_type, system_key, status, balance)
        values ('ESCROW', $1, 'active', 0);
      `, [`POKER_TABLE:${tableId}`]);
      if (failAfterInsert) throw new Error("fixture_create_rollback");
      return { ok: true, tableId };
    });
  } catch (error) {
    return { ok: false, code: error?.code || error?.message || "transaction_failed", tableId };
  }
}

async function authoritativeJoin(sql, userId, tableId, { barrier = null } = {}) {
  try {
    return await sql.begin(async (tx) => {
      if (barrier) await barrier();
      await lockUserTableSlots(tx, userId);
      const existingRows = await tx.unsafe(`
        select table_id, seat_no, stack
        from public.poker_seats
        where table_id = $1::uuid and user_id = $2::uuid and is_bot = false
        limit 1;
      `, [tableId, userId]);
      if (existingRows[0]) {
        await tx.unsafe("update public.poker_seats set last_seen_at = now() where table_id = $1::uuid and user_id = $2::uuid;", [tableId, userId]);
        return { ok: true, kind: "rejoin", tableId };
      }
      await assertActivePokerTableCapacity(tx, userId);
      const tableRows = await tx.unsafe("select id from public.poker_tables where id = $1::uuid and status = 'OPEN' for update;", [tableId]);
      if (!tableRows[0]) throw new Error("table_not_found");
      const stateRows = await tx.unsafe("select state from public.poker_state where table_id = $1::uuid for update;", [tableId]);
      const state = stateRows[0]?.state && typeof stateRows[0].state === "object" ? stateRows[0].state : { seats: [], stacks: {} };
      const nextState = {
        ...state,
        seats: [...(Array.isArray(state.seats) ? state.seats : []), { userId, seatNo: 1, isBot: false, stack: 100 }],
        stacks: { ...(state.stacks && typeof state.stacks === "object" ? state.stacks : {}), [userId]: 100 },
      };
      await tx.unsafe(`
        insert into public.poker_seats (table_id, user_id, seat_no, status, stack, is_bot)
        values ($1::uuid, $2::uuid, 1, 'ACTIVE', 100, false);
      `, [tableId, userId]);
      await tx.unsafe(`
        update public.poker_tables
        set has_human_participant = true, updated_at = now(), last_activity_at = now()
        where id = $1::uuid;
      `, [tableId]);
      await tx.unsafe("update public.poker_state set state = $2::jsonb, version = version + 1, updated_at = now() where table_id = $1::uuid;", [tableId, nextState]);
      await tx.unsafe(`
        insert into public.chips_transactions (tx_type, idempotency_key, payload_hash, metadata)
        values ('TABLE_BUY_IN', $1, repeat('a', 64), $2::jsonb);
      `, [`fixture-buy-in:${tableId}:${userId}`, { tableId, userId }]);
      return { ok: true, kind: "fresh", tableId };
    });
  } catch (error) {
    return { ok: false, code: error?.code || error?.message || "transaction_failed", tableId };
  }
}

async function postFixtureSystemTransfer(sql, { txType, idempotencyKey, metadata, fromKey, toKey, amount }) {
  await sql.begin(async (tx) => {
    const accountRows = await tx.unsafe(`
      select id, system_key from public.chips_accounts
      where account_type = 'SYSTEM' and system_key in ($1, $2)
      order by id for update;
    `, [fromKey, toKey]);
    assert.equal(accountRows.length, 2, "fixture system transfer requires both exact accounts");
    const idsByKey = new Map(accountRows.map((row) => [row.system_key, row.id]));
    const payload = `${idempotencyKey}|${fromKey}:${-amount}|${toKey}:${amount}`;
    const hashRows = await tx.unsafe("select encode(extensions.digest(convert_to($1, 'UTF8'), 'sha256'), 'hex') as value;", [payload]);
    const transactionRows = await tx.unsafe(`
      insert into public.chips_transactions (reference, description, metadata, idempotency_key, payload_hash, tx_type)
      values ($1, 'Disposable fixture transfer', $2::jsonb, $1, $3, $4::public.chips_tx_type)
      returning id;
    `, [idempotencyKey, metadata, hashRows[0].value, txType]);
    await tx.unsafe("update public.chips_accounts set balance = balance - $2 where id = $1::uuid;", [idsByKey.get(fromKey), amount]);
    await tx.unsafe("update public.chips_accounts set balance = balance + $2 where id = $1::uuid;", [idsByKey.get(toKey), amount]);
    await tx.unsafe(`
      insert into public.chips_entries (transaction_id, account_id, amount, metadata)
      values ($1::uuid, $2::uuid, $3, '{}'::jsonb), ($1::uuid, $4::uuid, $5, '{}'::jsonb);
    `, [transactionRows[0].id, idsByKey.get(fromKey), -amount, idsByKey.get(toKey), amount]);
  });
}

test("poker table slot queries keep bounded user-leading and creator-leading contracts", async () => {
  const source = await fs.readFile(sourcePath, "utf8");
  assert.match(source, /from public\.poker_seats s[\s\S]*where s\.user_id = \$1[\s\S]*limit \$\{boundedLimit\}/);
  assert.match(source, /from public\.poker_tables t[\s\S]*where t\.created_by = \$1[\s\S]*limit \$\{boundedLimit\}/);
  assert.match(source, /select distinct s\.table_id/);
  assert.match(source, /public\.poker_state ps[\s\S]*state -> 'seats'[\s\S]*state -> 'stacks'/);
  assert.match(source, /not exists \([\s\S]*public\.poker_seats/);
  assert.match(source, /not exists \([\s\S]*public\.chips_transactions/);
  assert.equal((source.match(/MAX_ACTIVE_POKER_TABLES = 4/g) || []).length, 1);
  assert.equal((source.match(/MAX_PENDING_POKER_TABLES = 4/g) || []).length, 1);
});

test("disposable PostgreSQL capability detects legacy schema then the committed migration on the next transaction", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    await ensurePoolMigrationFixture(sql);
    await sql.unsafe(BASE_SCHEMA);
    // Permit rerunning this destructive fixture in the same disposable test DB.
    await sql.unsafe("drop table if exists public.poker_access_policy;");
    await sql.begin(async (tx) => {
      assert.equal(await hasPokerPoolSchema(tx), false);
      assert.equal(await hasPokerPoolSchema(tx), false);
      assert.equal(Number((await tx`select 1 as usable;`)[0].usable), 1,
        "capability detection must not leave the legacy transaction aborted");
    });
    await sql.begin(async (tx) => tx.unsafe(await migrationSql()));
    await sql.begin(async (tx) => {
      assert.equal(await hasPokerPoolSchema(tx), true,
        "an earlier negative result must not be cached across transactions");
      const rows = await tx`select slow_threshold_ch from public.poker_access_policy where id = 1;`;
      assert.equal(Number(rows[0].slow_threshold_ch), 1_000_000_000);
    });
  }, { initialize: false });
});

test("disposable PostgreSQL proves concurrent Create/JOIN 4+4 limits, rejection and funded rejoin", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    const userId = fixtureUuid(1);
    const pendingBarrier = makeBarrier(8);
    const pendingResults = await Promise.all(
      Array.from({ length: 8 }, (_, index) => createPending(sql, userId, fixtureUuid(100 + index), { barrier: pendingBarrier })),
    );
    assert.equal(pendingResults.filter((result) => result.ok).length, MAX_PENDING_POKER_TABLES);
    assert.equal(pendingResults.filter((result) => !result.ok && result.code === "pending_table_limit").length, 4);
    assert.deepEqual(await countSlots(sql, userId), { active: 0, pending: 4 });

    const fifthPending = await createPending(sql, userId, fixtureUuid(200));
    assert.equal(fifthPending.ok, false);
    assert.equal(fifthPending.code, "pending_table_limit");
    assert.deepEqual(await countArtifacts(sql, fixtureUuid(200)), { tables: 0, states: 0, escrows: 0 });

    const acceptedPending = pendingResults.filter((result) => result.ok).map((result) => result.tableId);
    const firstJoins = await Promise.all(acceptedPending.slice(0, 2).map((tableId) => authoritativeJoin(sql, userId, tableId)));
    assert.equal(firstJoins.filter((result) => result.ok && result.kind === "fresh").length, 2, JSON.stringify(firstJoins));
    assert.deepEqual(await countSlots(sql, userId), { active: 2, pending: 2 });

    const additionalPending = await Promise.all([
      createPending(sql, userId, fixtureUuid(300)),
      createPending(sql, userId, fixtureUuid(301)),
    ]);
    assert.equal(additionalPending.filter((result) => result.ok).length, 2);
    assert.deepEqual(await countSlots(sql, userId), { active: 2, pending: 4 });

    const joinCandidates = acceptedPending.slice(2).concat(additionalPending.filter((result) => result.ok).map((result) => result.tableId));
    const boundedJoinBarrier = makeBarrier(joinCandidates.length);
    const boundedJoins = await Promise.all(joinCandidates.map((tableId) => authoritativeJoin(sql, userId, tableId, { barrier: boundedJoinBarrier })));
    assert.equal(boundedJoins.filter((result) => result.ok && result.kind === "fresh").length, 2);
    assert.equal(boundedJoins.filter((result) => !result.ok && result.code === "active_table_limit").length, 2);
    assert.deepEqual(await countSlots(sql, userId), { active: 4, pending: 2 });

    const fifthJoinTable = fixtureUuid(400);
    assert.equal((await createPending(sql, userId, fifthJoinTable)).ok, true);
    const beforeRejectedJoin = await sql`select count(*)::int as count from public.chips_transactions;`;
    const fifthJoin = await authoritativeJoin(sql, userId, fifthJoinTable);
    assert.equal(fifthJoin.ok, false);
    assert.equal(fifthJoin.code, "active_table_limit");
    const afterRejectedJoin = await sql`select count(*)::int as count from public.chips_transactions;`;
    assert.equal(Number(afterRejectedJoin[0].count), Number(beforeRejectedJoin[0].count));
    assert.equal(Number((await sql`select count(*)::int as count from public.poker_seats where user_id = ${userId} and is_bot = false;`)[0].count), 4);

    const activeTableId = acceptedPending[0];
    const beforeRejoin = await sql`select count(*)::int as seats from public.poker_seats where user_id = ${userId};`;
    const fundedRejoin = await authoritativeJoin(sql, userId, activeTableId);
    assert.deepEqual(fundedRejoin, { ok: true, kind: "rejoin", tableId: activeTableId });
    const afterRejoin = await sql`select count(*)::int as seats from public.poker_seats where user_id = ${userId};`;
    assert.equal(Number(afterRejoin[0].seats), Number(beforeRejoin[0].seats));

    const rollbackTable = fixtureUuid(500);
    const rollback = await createPending(sql, userId, rollbackTable, { failAfterInsert: true });
    assert.equal(rollback.ok, false);
    assert.deepEqual(await countArtifacts(sql, rollbackTable), { tables: 0, states: 0, escrows: 0 });
    const markerRows = await sql`select count(*)::int as count from public.poker_tables where id = ${activeTableId} and has_human_participant is true;`;
    assert.equal(Number(markerRows[0].count), 1, "accepted first JOIN must transfer pending to active and set the marker");
  });
});

test("disposable PostgreSQL proves settled automatic SLOW races safely with Admin override", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    const userId = fixtureUuid(2);
    await sql.unsafe(`
      insert into public.chips_accounts (account_type, user_id, status, balance, poker_auto_class, poker_access_override, poker_access_revision)
      values ('USER', $1::uuid, 'active', 1000000000, 'NORMAL', 'AUTO', 1);
    `, [userId]);
    const settledStack = 1000000000;
    await Promise.all([
      sql.begin(async (tx) => {
        await tx.unsafe(`
          update public.chips_accounts account
          set poker_auto_class = case
                when $2::bigint >= policy.slow_threshold_ch then 'SLOW'
                else account.poker_auto_class
              end,
              poker_auto_slow_at = case
                when $2::bigint >= policy.slow_threshold_ch then coalesce(account.poker_auto_slow_at, now())
                else account.poker_auto_slow_at
              end,
              poker_access_revision = account.poker_access_revision + 1
          from public.poker_access_policy policy
          where account.user_id = $1::uuid and account.account_type = 'USER';
        `, [userId, settledStack]);
      }),
      sql.begin(async (tx) => {
        await tx.unsafe(`
          update public.chips_accounts
          set poker_access_override = 'FORCE_NORMAL', poker_access_revision = poker_access_revision + 1
          where user_id = $1::uuid and account_type = 'USER';
        `, [userId]);
      }),
    ]);
    const rows = await sql.unsafe(`
      select poker_auto_class, poker_access_override, poker_access_revision, poker_auto_slow_at
      from public.chips_accounts where user_id = $1::uuid;
    `, [userId]);
    assert.equal(rows[0].poker_auto_class, "SLOW");
    assert.equal(rows[0].poker_access_override, "FORCE_NORMAL");
    assert.equal(Number(rows[0].poker_access_revision), 3);
    assert.ok(rows[0].poker_auto_slow_at, "settled threshold transition must retain durable audit time");
  });
});

test("disposable PostgreSQL proves hourly ledger refill, exact mapping, idempotency and pool isolation", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    const callRefill = async () => (await sql`select public.poker_bot_pool_refill_hourly() as summary;`)[0].summary;
    const setTier = async (buyIn, enabled) => sql`
      update public.poker_bot_tier_policy set enabled = ${enabled} where buy_in = ${buyIn};
    `;
    const refillRowsFor = async (systemKey) => sql`
      select id, idempotency_key, payload_hash, metadata
      from public.chips_transactions
      where tx_type = 'MINT'::public.chips_tx_type
        and metadata ->> 'purpose' = 'poker_pool_refill'
        and metadata ->> 'bankrollSystemKey' = ${systemKey}
      order by created_at, id;
    `;

    const identityRows = await sql.unsafe("select system_identifier::text as value from pg_catalog.pg_control_system();");
    await sql`update public.poker_bot_refill_control set expected_system_identifier = 'wrong-database' where id = 1;`;
    await assert.rejects(
      () => callRefill(),
      (error) => error?.code === "P1029" && /database_identity_mismatch/.test(error?.message || ""),
      "database identity mismatch fails closed before refill processing",
    );
    assert.equal(Number((await sql`select count(*)::int as count from public.chips_transactions where metadata ->> 'purpose' = 'poker_pool_refill';`)[0].count), 0);
    await sql`update public.poker_bot_refill_control set expected_system_identifier = ${identityRows[0].value} where id = 1;`;

    await setTier(100, true);
    const disabledSummary = await callRefill();
    assert.equal(disabledSummary.status, "disabled", "global control is a default-off kill switch");
    assert.equal(Number((await sql`select count(*)::int as count from public.chips_transactions where metadata ->> 'purpose' = 'poker_pool_refill';`)[0].count), 0);
    await sql`update public.poker_bot_refill_control set enabled = true where id = 1;`;

    await setTier(100, false);
    const disabledTierSummary = await callRefill();
    assert.equal(disabledTierSummary.pools.length, 0, "disabled tiers are not processed");
    assert.equal(Number((await sql`select count(*)::int as count from public.chips_transactions where metadata ->> 'purpose' = 'poker_pool_refill';`)[0].count), 0);

    await setTier(100, true);
    await postFixtureSystemTransfer(sql, {
      txType: "MINT",
      idempotencyKey: "fixture-threshold-normal-100",
      metadata: { purpose: "fixture_threshold" },
      fromKey: "GENESIS",
      toKey: "POKER_BOT_BANKROLL_100",
      amount: 2000,
    });
    await postFixtureSystemTransfer(sql, {
      txType: "MINT",
      idempotencyKey: "fixture-threshold-slow-100",
      metadata: { purpose: "fixture_threshold" },
      fromKey: "GENESIS",
      toKey: "POKER_BOT_SLOW_BANKROLL_100",
      amount: 1000,
    });
    let thresholdSummary = await callRefill();
    assert.deepEqual(thresholdSummary.pools.map((pool) => pool.status), ["no_op", "no_op"], "balance at threshold is a no-op for both pool classes");
    await postFixtureSystemTransfer(sql, {
      txType: "MINT",
      idempotencyKey: "fixture-above-threshold-normal-100",
      metadata: { purpose: "fixture_threshold" },
      fromKey: "GENESIS",
      toKey: "POKER_BOT_BANKROLL_100",
      amount: 500,
    });
    thresholdSummary = await callRefill();
    assert.deepEqual(thresholdSummary.pools.map((pool) => pool.status), ["no_op", "no_op"], "balance above threshold is a no-op");
    assert.equal(Number((await sql`select count(*)::int as count from public.chips_transactions where metadata ->> 'purpose' = 'poker_pool_refill';`)[0].count), 0);

    await postFixtureSystemTransfer(sql, {
      txType: "BURN",
      idempotencyKey: "fixture-spend-threshold-normal-100",
      metadata: { purpose: "fixture_spend" },
      fromKey: "POKER_BOT_BANKROLL_100",
      toKey: "HOUSE",
      amount: 2500,
    });
    await postFixtureSystemTransfer(sql, {
      txType: "BURN",
      idempotencyKey: "fixture-spend-threshold-slow-100",
      metadata: { purpose: "fixture_spend" },
      fromKey: "POKER_BOT_SLOW_BANKROLL_100",
      toKey: "HOUSE",
      amount: 1000,
    });
    const exactSummary = await callRefill();
    assert.deepEqual(exactSummary.pools.map((pool) => [pool.systemKey, pool.amount, pool.status]), [
      ["POKER_BOT_BANKROLL_100", 5000, "refilled"],
      ["POKER_BOT_SLOW_BANKROLL_100", 2000, "refilled"],
    ]);
    const exactRows = await refillRowsFor("POKER_BOT_BANKROLL_100");
    assert.equal(exactRows.length, 1);
    assert.match(exactRows[0].idempotency_key, /^poker-pool-refill:POKER_BOT_BANKROLL_100:1:\d{4}-\d\d-\d\dT\d\d:00:00\.000Z$/);
    assert.match(exactRows[0].payload_hash, /^[0-9a-f]{64}$/);
    assert.deepEqual(exactRows[0].metadata, {
      purpose: "poker_pool_refill",
      bankrollSystemKey: "POKER_BOT_BANKROLL_100",
      buyIn: 100,
      poolClass: "NORMAL",
      policyRevision: 1,
      bucket: exactSummary.bucket,
    });
    const ledgerRows = await sql`
      select t.tx_type::text as tx_type, t.metadata, t.idempotency_key, t.payload_hash,
             count(e.id)::int as entry_count, coalesce(sum(e.amount), 0)::bigint as total,
             count(distinct r.transaction_id)::int as registry_count,
             min(e.entry_seq)::bigint as min_entry_seq, max(e.entry_seq)::bigint as max_entry_seq
      from public.chips_transactions t
      left join public.chips_entries e on e.transaction_id = t.id
      left join public.chips_transaction_idempotency r on r.transaction_id = t.id
      where t.id = ${exactRows[0].id}::uuid
      group by t.id;
    `;
    assert.equal(ledgerRows[0].tx_type, "MINT");
    assert.equal(Number(ledgerRows[0].entry_count), 2);
    assert.equal(Number(ledgerRows[0].total), 0);
    assert.equal(Number(ledgerRows[0].registry_count), 1, "the transaction insert trigger must create the idempotency registry row");
    assert.ok(Number(ledgerRows[0].min_entry_seq) > 0 && Number(ledgerRows[0].max_entry_seq) > 0,
      "the existing entry-sequence trigger assigns positive per-account sequences");
    assert.equal(Number((await sql`select balance from public.chips_accounts where system_key = 'POKER_BOT_BANKROLL_100';`)[0].balance), 5000);
    assert.equal(Number((await sql`select balance from public.chips_accounts where system_key = 'GENESIS';`)[0].balance), 1000000000 - 2000 - 500 - 1000 - 5000 - 2000);

    await postFixtureSystemTransfer(sql, {
      txType: "BURN",
      idempotencyKey: "fixture-same-hour-spend-normal-100",
      metadata: { purpose: "fixture_spend" },
      fromKey: "POKER_BOT_BANKROLL_100",
      toKey: "HOUSE",
      amount: 5000,
    });
    const beforeSameHour = await refillRowsFor("POKER_BOT_BANKROLL_100");
    const sameHourSummary = await callRefill();
    assert.equal(sameHourSummary.pools.find((pool) => pool.systemKey === "POKER_BOT_BANKROLL_100").status, "replay");
    assert.equal((await refillRowsFor("POKER_BOT_BANKROLL_100")).length, beforeSameHour.length, "same-hour depleted pool cannot receive a second MINT");
    await Promise.all([callRefill(), callRefill()]);
    assert.equal((await refillRowsFor("POKER_BOT_BANKROLL_100")).length, beforeSameHour.length, "concurrent same-hour calls cannot duplicate a pool MINT");

    await postFixtureSystemTransfer(sql, {
      txType: "MINT",
      idempotencyKey: "fixture-prior-hour-normal-500",
      metadata: {
        purpose: "poker_pool_refill",
        bankrollSystemKey: "POKER_BOT_BANKROLL",
        buyIn: 500,
        poolClass: "NORMAL",
        policyRevision: 1,
        bucket: new Date(Date.parse(exactSummary.bucket) - 60 * 60 * 1000).toISOString(),
      },
      fromKey: "GENESIS",
      toKey: "POKER_BOT_BANKROLL",
      amount: 10000,
    });
    await postFixtureSystemTransfer(sql, {
      txType: "BURN",
      idempotencyKey: "fixture-prior-hour-spend-normal-500",
      metadata: { purpose: "fixture_spend" },
      fromKey: "POKER_BOT_BANKROLL",
      toKey: "HOUSE",
      amount: 10000,
    });
    await setTier(500, true);
    await postFixtureSystemTransfer(sql, {
      txType: "MINT",
      idempotencyKey: "fixture-prior-hour-slow-500",
      metadata: {
        purpose: "poker_pool_refill",
        bankrollSystemKey: "POKER_BOT_SLOW_BANKROLL_500",
        buyIn: 500,
        poolClass: "SLOW",
        policyRevision: 1,
        bucket: new Date(Date.parse(exactSummary.bucket) - 60 * 60 * 1000).toISOString(),
      },
      fromKey: "GENESIS",
      toKey: "POKER_BOT_SLOW_BANKROLL_500",
      amount: 5000,
    });
    await postFixtureSystemTransfer(sql, {
      txType: "BURN",
      idempotencyKey: "fixture-prior-hour-spend-slow-500",
      metadata: { purpose: "fixture_spend" },
      fromKey: "POKER_BOT_SLOW_BANKROLL_500",
      toKey: "HOUSE",
      amount: 5000,
    });
    const nextHourSummary = await callRefill();
    assert.deepEqual(nextHourSummary.pools.filter((pool) => pool.buyIn === 500).map((pool) => [pool.systemKey, pool.status]), [
      ["POKER_BOT_BANKROLL", "refilled"],
      ["POKER_BOT_SLOW_BANKROLL_500", "refilled"],
    ], "prior-hour ledger rows do not block a later UTC bucket refill");
    const normal500Rows = await refillRowsFor("POKER_BOT_BANKROLL");
    assert.equal(normal500Rows.length, 2);
    assert.equal(normal500Rows.some((row) => row.metadata.bucket === nextHourSummary.bucket), true);

    await sql`update public.poker_bot_tier_policy set enabled = false;`;
    await setTier(10000000, true);
    const mappedSummary = await callRefill();
    const mappingPairs = mappedSummary.pools
      .filter((pool) => pool.buyIn === 10000000)
      .map((pool) => [pool.poolClass, pool.systemKey, pool.status]);
    assert.deepEqual(mappingPairs, [
      ["NORMAL", "POKER_BOT_BANKROLL_10000000", "refilled"],
      ["SLOW", "POKER_BOT_SLOW_BANKROLL_10000000", "refilled"],
    ], "maximum canonical tier keeps exact NORMAL/SLOW pool keys");

    await sql`update public.poker_bot_tier_policy set enabled = false;`;
    await setTier(1000, true);
    await setTier(5000, true);
    await sql`delete from public.chips_accounts where account_type = 'SYSTEM' and system_key = 'POKER_BOT_BANKROLL_1000';`;
    await sql`update public.chips_accounts set status = 'closed' where system_key = 'POKER_BOT_SLOW_BANKROLL_1000';`;
    await sql`delete from public.poker_bot_tier_policy where buy_in = 250;`;
    await sql`delete from public.chips_accounts where account_type = 'SYSTEM' and system_key = 'POKER_BOT_BANKROLL_250';`;
    await sql`
      insert into public.poker_bot_tier_policy (
        buy_in, enabled, normal_refill_threshold_ch, normal_refill_amount_ch,
        slow_refill_threshold_ch, slow_refill_amount_ch
      ) values (250, true, 100, 200, 100, 200);
    `;
    await sql`insert into public.chips_accounts (account_type, system_key, status, balance) values ('SYSTEM', 'POKER_BOT_BANKROLL_250', 'active', 0);`;

    await sql.unsafe(`
      create function public.fixture_fail_specific_poker_refill_entry()
      returns trigger
      language plpgsql
      as $fixture$
      begin
        if exists (
          select 1 from public.chips_transactions as tx
          where tx.id = new.transaction_id
            and tx.metadata ->> 'bankrollSystemKey' = 'POKER_BOT_BANKROLL_5000'
        ) then
          raise exception using errcode = 'P9999', message = 'fixture_pool_entry_failure';
        end if;
        return new;
      end;
      $fixture$;
      create trigger fixture_fail_specific_poker_refill_entry_trg
      before insert on public.chips_entries
      for each row execute function public.fixture_fail_specific_poker_refill_entry();
    `);
    const genesisBeforeIsolatedFailure = Number((await sql`select balance from public.chips_accounts where system_key = 'GENESIS';`)[0].balance);
    const concurrentSummaries = await Promise.all([callRefill(), callRefill()]);
    const isolatedSummary = concurrentSummaries.find((summary) => summary.status === "processed");
    assert.ok(isolatedSummary, "one concurrent invocation must process independent eligible pools");
    assert.equal(isolatedSummary.pools.find((pool) => pool.buyIn === 1000 && pool.poolClass === "NORMAL").status, "failed");
    assert.equal(isolatedSummary.pools.find((pool) => pool.buyIn === 1000 && pool.poolClass === "SLOW").status, "failed");
    assert.deepEqual(isolatedSummary.pools.filter((pool) => pool.buyIn === 5000).map((pool) => pool.status), ["failed", "refilled"], "a mid-ledger failure rolls back only its pool and does not block the independent SLOW pool");
    assert.equal(isolatedSummary.pools.find((pool) => pool.buyIn === 5000 && pool.poolClass === "NORMAL").error, "fixture_pool_entry_failure");
    assert.equal((await refillRowsFor("POKER_BOT_BANKROLL_5000")).length, 0, "the failed pool's transaction and idempotency registry entry roll back");
    assert.equal((await refillRowsFor("POKER_BOT_SLOW_BANKROLL_5000")).length, 1, "the independent successful pool commits exactly once");
    assert.equal(Number((await sql`select balance from public.chips_accounts where system_key = 'POKER_BOT_BANKROLL_5000';`)[0].balance), 0,
      "the failed pool balance delta rolls back with its transaction");
    assert.equal(Number((await sql`select balance from public.chips_accounts where system_key = 'POKER_BOT_SLOW_BANKROLL_5000';`)[0].balance), 50000);
    const genesisAfterIsolatedFailure = Number((await sql`select balance from public.chips_accounts where system_key = 'GENESIS';`)[0].balance);
    assert.equal(genesisBeforeIsolatedFailure - genesisAfterIsolatedFailure, 50000,
      "only the independent committed pool debits GENESIS");
    await sql.unsafe("drop trigger fixture_fail_specific_poker_refill_entry_trg on public.chips_entries;");
    await sql.unsafe("drop function public.fixture_fail_specific_poker_refill_entry();");
    assert.equal(isolatedSummary.pools.some((pool) => pool.buyIn === 250), false, "non-canonical enabled policy is ignored");
    assert.equal((await refillRowsFor("POKER_BOT_BANKROLL_250")).length, 0, "the function never MINTs to an arbitrary SYSTEM account");
    assert.equal((await refillRowsFor("POKER_BOT_BANKROLL_1000")).length, 0);
    assert.equal((await refillRowsFor("POKER_BOT_SLOW_BANKROLL_1000")).length, 0);
    await assert.rejects(
      () => sql`update public.poker_bot_tier_policy set normal_refill_amount_ch = 0 where buy_in = 5000;`,
      (error) => error?.code === "23514",
      "malformed refill policy remains rejected by the policy CHECK constraint",
    );
  });
});

test("disposable PostgreSQL bounds a contended pool lock and commits an independent pool", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    await sql`update public.poker_bot_refill_control set enabled = true where id = 1;`;
    await sql`update public.poker_bot_tier_policy set enabled = (buy_in = 100);`;

    const holder = postgres(dbUrl, { max: 1, idle_timeout: 0, connect_timeout: 5 });
    let signalLockAcquired;
    let rejectLockAcquisition;
    let releaseHolder;
    const lockAcquired = new Promise((resolve, reject) => {
      signalLockAcquired = resolve;
      rejectLockAcquisition = reject;
    });
    const holdTransaction = new Promise((resolve) => { releaseHolder = resolve; });
    const lockTask = holder.begin(async (tx) => {
      try {
        const lockedRows = await tx`
          select id from public.chips_accounts
          where account_type = 'SYSTEM' and system_key = 'POKER_BOT_BANKROLL_100'
          for update;
        `;
        assert.equal(lockedRows.length, 1, "the required NORMAL pool account exists in the disposable fixture");
        signalLockAcquired();
      } catch (error) {
        rejectLockAcquisition(error);
        throw error;
      }
      await holdTransaction;
    });

    try {
      await lockAcquired;
      await sql.unsafe("set lock_timeout = '0';");
      await sql.unsafe("set statement_timeout = '8s';");
      const summary = (await sql`select public.poker_bot_pool_refill_hourly() as summary;`)[0].summary;
      assert.equal(summary.status, "processed");
      const lockedPool = summary.pools.find((pool) => pool.systemKey === "POKER_BOT_BANKROLL_100");
      assert.equal(lockedPool.status, "failed");
      assert.equal(lockedPool.sqlState, "55P03", "the locked pool fails through PostgreSQL's bounded lock timeout");
      const independentPool = summary.pools.find((pool) => pool.systemKey === "POKER_BOT_SLOW_BANKROLL_100");
      assert.equal(independentPool.status, "refilled");
      assert.equal(Number(independentPool.amount), 2000);

      const committed = await sql`
        select tx.id, tx.idempotency_key, entry.account_id, account.system_key, entry.amount
        from public.chips_transactions as tx
        join public.chips_entries as entry on entry.transaction_id = tx.id
        join public.chips_accounts as account on account.id = entry.account_id
        where tx.tx_type = 'MINT'::public.chips_tx_type
          and tx.metadata ->> 'purpose' = 'poker_pool_refill'
          and tx.metadata ->> 'bankrollSystemKey' = 'POKER_BOT_SLOW_BANKROLL_100';
      `;
      assert.equal(committed.length, 2, "the independent pool commits one MINT with its two ledger entries");
      assert.equal(Number((await sql`
        select count(*)::int as count
        from public.chips_transactions
        where tx_type = 'MINT'::public.chips_tx_type
          and metadata ->> 'purpose' = 'poker_pool_refill'
          and metadata ->> 'bankrollSystemKey' = 'POKER_BOT_SLOW_BANKROLL_100';
      `)[0].count), 1, "the independent pool receives exactly one committed MINT");
      assert.equal(new Set(committed.map((entry) => entry.id)).size, 1);
      assert.equal(new Set(committed.map((entry) => entry.idempotency_key)).size, 1);
      assert.equal(committed.reduce((sum, entry) => sum + Number(entry.amount), 0), 0, "the committed MINT is balanced");
      assert.deepEqual(
        committed.map((entry) => [entry.system_key, Number(entry.amount)]).sort(),
        [["GENESIS", -2000], ["POKER_BOT_SLOW_BANKROLL_100", 2000]].sort(),
      );
      assert.equal(Number((await sql`select balance from public.chips_accounts where system_key = 'POKER_BOT_BANKROLL_100';`)[0].balance), 0,
        "the failed pool remains unchanged");
      assert.equal(Number((await sql`
        select count(*)::int as count
        from public.chips_transactions
        where tx_type = 'MINT'::public.chips_tx_type
          and metadata ->> 'purpose' = 'poker_pool_refill'
          and metadata ->> 'bankrollSystemKey' = 'POKER_BOT_BANKROLL_100';
      `)[0].count), 0, "the failed pool leaves no committed MINT");
      assert.equal(Number((await sql`select balance from public.chips_accounts where system_key = 'POKER_BOT_SLOW_BANKROLL_100';`)[0].balance), 2000,
        "the independent pool balance commits");
    } finally {
      releaseHolder();
      await lockTask.catch(() => {});
      await holder.end({ timeout: 5 });
    }
  });
});

test("local PostgreSQL EXPLAIN confirms bounded indexed active and pending access paths", { skip: !dbUrl }, async () => {
  await withFixture(async (sql) => {
    const targetUser = fixtureUuid(9000);
    const unrelatedUser = fixtureUuid(9001);
    for (let index = 0; index < 12; index += 1) {
      await sql.unsafe(`
        insert into public.poker_tables (id, created_by, status, lifecycle_kind, has_human_participant)
        values ($1::uuid, $2::uuid, 'OPEN', 'STANDARD', $3);
      `, [fixtureUuid(10000 + index), targetUser, index < 6]);
      await sql.unsafe(
        "insert into public.poker_state (table_id, state) values ($1::uuid, $2::jsonb);",
        [fixtureUuid(10000 + index), index < 6 ? { seats: [{ userId: targetUser, seatNo: 1 }], stacks: { [targetUser]: 100 } } : { seats: [], stacks: {} }],
      );
      if (index < 6) {
        await sql.unsafe("insert into public.poker_seats (table_id, user_id, seat_no, status, stack, is_bot) values ($1::uuid, $2::uuid, 1, 'ACTIVE', 100, false);", [fixtureUuid(10000 + index), targetUser]);
      }
    }
    await sql.unsafe(`
      insert into public.poker_tables (created_by, status, lifecycle_kind, has_human_participant)
      select $1::uuid, 'OPEN', 'STANDARD', false from generate_series(1, 5000);
    `, [unrelatedUser]);
    await sql.unsafe(`
      insert into public.poker_tables (created_by, status, lifecycle_kind, has_human_participant)
      select $1::uuid, 'OPEN', 'STANDARD', false from generate_series(1, 5000);
    `, [fixtureUuid(9002)]);
    await sql.unsafe(`
      insert into public.poker_seats (table_id, user_id, seat_no, status, stack, is_bot)
      select id, $1::uuid, 1, 'ACTIVE', 100, false
      from public.poker_tables where created_by = $1::uuid limit 5000;
    `, [unrelatedUser]);
    await sql.unsafe(`
      insert into public.poker_state (table_id, state)
      select id, '{"seats": [], "stacks": {}}'::jsonb
      from public.poker_tables where created_by = $1::uuid;
    `, [fixtureUuid(9002)]);
    await sql.unsafe("analyze public.poker_tables; analyze public.poker_seats; analyze public.poker_state; analyze public.chips_transactions;");

    const counts = await countSlots(sql, targetUser);
    assert.deepEqual(counts, { active: 5, pending: 5 }, "counts must stop at the five-row bound");

    const activeExplain = await sql.unsafe(`
      explain (analyze, buffers, format json)
      select count(*)::int as count
      from (
        select distinct s.table_id
        from public.poker_seats s
        join public.poker_tables t on t.id = s.table_id
        where s.user_id = $1::uuid
          and s.status = 'ACTIVE'
          and coalesce(s.is_bot, false) = false
          and coalesce(s.stack, 0) > 0
          and upper(coalesce(t.status, 'OPEN')) not in ('CLOSED', 'TERMINAL')
        limit 5
      ) active_tables;
    `, [targetUser]);
    const pendingExplain = await sql.unsafe(`
      explain (analyze, buffers, format json)
      select count(*)::int as count
      from (
        select t.id
        from public.poker_tables t
        where t.created_by = $1::uuid
          and t.status = 'OPEN'
          and t.lifecycle_kind = 'STANDARD'
          and t.has_human_participant = false
          and exists (select 1 from public.poker_state ps where ps.table_id = t.id and ps.state -> 'seats' = '[]'::jsonb and ps.state -> 'stacks' = '{}'::jsonb)
          and not exists (select 1 from public.poker_seats s where s.table_id = t.id)
          and not exists (select 1 from public.chips_transactions ct where ct.metadata ->> 'tableId' = t.id::text)
        limit 5
      ) pending_tables;
    `, [targetUser]);
    const activePlan = activeExplain[0]["QUERY PLAN"][0];
    const pendingPlan = pendingExplain[0]["QUERY PLAN"][0];
    const activeNodes = planNodes(activePlan.Plan);
    const pendingNodes = planNodes(pendingPlan.Plan);
    assert.ok(activeNodes.some((node) => node["Index Name"] === "poker_seats_user_id_active_human_idx"), "active plan must use user-leading index");
    assert.ok(pendingNodes.some((node) => node["Index Name"] === "poker_tables_created_by_pending_standard_idx"), "pending plan must use creator-leading index");
    for (const nodes of [activeNodes, pendingNodes]) {
      assert.equal(nodes.some((node) => node["Node Type"] === "Seq Scan" && /poker_(seats|tables)/i.test(String(node["Relation Name"] || ""))), false, "fresh count must not scan global seats/tables");
      assert.equal(nodes.some((node) => node["Node Type"] === "Limit" && Number(node["Actual Rows"]) > 5), false, "bounded count must stop at five qualifying rows");
    }
  });
});
