-- Base chips schema to support Netlify Functions
create extension if not exists "pgcrypto";

do $$
begin
  if not exists (
    select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'chips_account_type' and n.nspname = 'public'
  ) then
    create type public.chips_account_type as enum ('USER', 'SYSTEM', 'ESCROW');
  end if;
  if not exists (
    select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'chips_account_status' and n.nspname = 'public'
  ) then
    create type public.chips_account_status as enum ('active', 'frozen', 'closed');
  end if;
  if not exists (
    select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'chips_tx_type' and n.nspname = 'public'
  ) then
    create type public.chips_tx_type as enum ('MINT', 'BURN', 'BUY_IN', 'CASH_OUT', 'RAKE_FEE', 'PRIZE_PAYOUT');
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'chips_accounts'
  ) then
    create table public.chips_accounts (
      id uuid primary key default gen_random_uuid(),
      user_id uuid references auth.users (id),
      system_key text,
      account_type public.chips_account_type not null,
      status public.chips_account_status not null default 'active',
      balance bigint not null default 0,
      next_entry_seq bigint not null default 1,
      created_at timestamptz not null default timezone('utc', now()),
      updated_at timestamptz not null default timezone('utc', now())
    );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'chips_transactions'
  ) then
    create table public.chips_transactions (
      id uuid primary key default gen_random_uuid(),
      tx_type public.chips_tx_type not null,
      idempotency_key text not null,
      payload_hash text not null,
      reference text,
      description text,
      metadata jsonb not null default '{}'::jsonb,
      created_by uuid,
      created_at timestamptz not null default timezone('utc', now())
    );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'chips_entries'
  ) then
    create table public.chips_entries (
      id bigint generated by default as identity primary key,
      transaction_id uuid not null references public.chips_transactions (id) on delete cascade,
      account_id uuid not null references public.chips_accounts (id),
      entry_seq bigint not null,
      amount bigint not null,
      metadata jsonb not null default '{}'::jsonb,
      created_at timestamptz not null default timezone('utc', now())
    );
  end if;
end $$;

create unique index if not exists chips_accounts_user_unique_partial
  on public.chips_accounts (user_id)
  where account_type = 'USER';

create unique index if not exists chips_accounts_system_key_unique_partial
  on public.chips_accounts (system_key)
  where system_key is not null;

create index if not exists chips_entries_account_seq_idx on public.chips_entries (account_id, entry_seq);
create index if not exists chips_transactions_idempotency_idx on public.chips_transactions (idempotency_key);

alter table public.chips_accounts
  add constraint if not exists chips_accounts_user_system_exclusive check (
    (account_type = 'USER' and user_id is not null and system_key is null)
    or (account_type <> 'USER' and user_id is null and system_key is not null)
  );

alter table public.chips_transactions
  add constraint if not exists chips_transactions_idempotency_key_present check (length(idempotency_key) > 0),
  add constraint if not exists chips_transactions_payload_hash_present check (length(payload_hash) > 0);

alter table public.chips_entries
  add constraint if not exists chips_entries_non_zero_amount check (amount <> 0),
  add constraint if not exists chips_entries_entry_seq_positive check (entry_seq > 0);
