name: Validate games catalog

on:
  pull_request:

jobs:
  validate:
    name: Validate js/games.json
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install jsonschema
        run: pip install jsonschema

      - name: Validate games catalog
        run: python -m jsonschema -i js/games.json js/games.schema.json
